### ISSUE TITLE
5.0.0-alpha3 Feature parity

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#2117]
See https://www.elastic.co/guide/en/elasticsearch/reference/master/release-notes-5.0.0-alpha3.html

### CAT API
- [x] Row-centric output for _cat/fielddata #18068 (issue: #10249)

### Inner Hits
- [x] Drop top level inner hits in favour of inner hits defined in the query dsl #17816 (issue: #11118). demonstrate with example of descending `has_child` queries with `inner_hits`

### Plugin Delete By Query
- [x] Remove Delete-By-Query plugin #18516 (issue: #18469). Update Delete By Query to use API instead of plugin

### Search
- [x] Refactor of query profile classes to make way for other profile implementations #18370 (issue: #10538). Renaming of properties on Profile

### Ingest
- [x] Add a Sort ingest processor #17999
- [x] Add date_index_name processor #17973 (issue: #17814)

### Reindex API
Port Delete By Query to Reindex infrastructure #18329 (issue: #16883)

### Stats
- [x] Extend field stats to report searchable/aggregatable fields #17980 (issue: #17750)

### Allocation

- [x] Add the shard’s store status to the explain API #17689 (issue: #17372)

### CAT API

- [x]  Add node name to Cat Recovery #18187 (issue: #8041)
- [x] Add support for documented byte/size units and for micros as a time unit in _cat API #17779

### Query DSL

- [x] Don’t allow fuzziness for multi_match types cross_fields, phrase and phrase_prefix #18322 (issues: #6866, #7764)

### Search

- [x] Introduces GeoValidationMethod to GeoDistanceSortBuilder #18036 - Deprecate coerce and ignore_malformed on `GeoPolygonQuery`, `GeoDistanceRangeQuery`, `GeoDistanceQuery` and `GeoBoundingBoxQuery` in favour of validation method
