### ISSUE TITLE
6.0 GA checklist

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#2903]
- [x] Go over all the breaking changes again to make absolutely sure we have not missed anything - @codebrain (see https://github.com/elastic/elasticsearch-net/issues/2923)
  - [x] Go over all the current `[Obsolete()]` and make sure they are still relevant. @codebrain 
  - [ ] Apply new `[Obsolete()]` where they make sense. @codebrain 
- [x] Go over all the TODO's in the code base and make sure we tackled everything we can.
- [x] Internalize our JSON.NET dependency (https://github.com/elastic/elasticsearch-net/tree/feature/dependencies-scrub) - @Mpdreamz 
  - [x] pending results of previous branch make sure the new `NEST.Json.Net` package is part of the build.
  - [x] reserve the `NEST` prefix on Nuget
- [x] Generate a binary breaking changes document like we did for 2.x and 5.x. 
- [x] Use the binary diff to validate all visibility changes @codebrain
- [x] Check names of items and ensure we are happy with them - e.g. PropertyVisitor -> DocumentPropertyVisitor
- [x] Overloads for `ConnectionSettings`
- [x] Go over issues that would affect 6.0.0 e.g. #2840 @russcam
- [x] Regenerate documentation - @russcam
- [x] Cut `6.x` branch
- [x] Release notes
- [x] Blog post
- [x] Tweet!

# missing features

- [x] Index sorting (PR is open: https://github.com/elastic/elasticsearch-net/pull/2910)

**Comment by andrewrimmer** [comment]
We are looking to migrate our cluster to 6.0.

Will the latest stable NEST work against 6.0? Or would it be safer to wait for NEST 6? Are there any rough timelines?

**Comment by russcam** [comment]
Hey @andrewrimmer, the latest stable NEST 5.x on nuget is not tested or supported with 6.0. The 6.0.0-alpha1 package was tested against 6.0.0-alpha1 Elasticsearch, however, there have been quite a few changes in Elasticsearch since that release.

We're working on the 6.0.0 release of the client as the highest priority right now, and expect to GA release hopefully this week or next, so long as we don't find any showstoppers! In the meantime and if you're eager to get going with NEST 6.x, [we have the canary releases on MyGet, which will contain the latest from master](https://www.myget.org/feed/elasticsearch-net-next/package/nuget/NEST) (they start from `6.1.0-<prerelease>` as canary always assumes it's the next minor).

**Comment by kbandrew** [comment]
Thanks @russcam.

I have given 6.1 a try but when I do a basic index operation I get "ProtocolViolationException: When performing a write operation with AllowWriteStreamBuffering set to false, you must either set ContentLength to a non-negative number or set SendChunked to true.". Should I be reporting this as an issue or is this just part and parcel of using the pre-release canary release?

**Comment by russcam** [comment]
Please report as a bug @kbandrew, relates to #2891. Does this happen on all requests?

**Comment by kbandrew** [comment]
@russcam this happens on all requests and is using a brand new installation of Elasticsearch 6 and a hello world index & search example. Swapping out NEST 6.1 with the latest 5.5 stable release makes it work without any code changes.

I will create an issue for it.

**Comment by russcam** [comment]
Thank you @kbandrew; I'll fix it today 👍

**Comment by kbandrew** [comment]
Smart. I will keep an eye out for the next canary release and will re-test.

**Comment by neotek** [comment]
Any news on this?
What is the current expected GA/RC release date? We would like to plan the migration to ES 6.

**Comment by russcam** [comment]
Hey @neotek, we are looking to publish a 6.0.0-beta1 to nuget shortly. This beta is very near to what we anticipate the GA release will be, but we wuld like to publish it to nuget in order to garner wider feedback. We do also publish [CI canary releases to MyGet](https://www.myget.org/feed/elasticsearch-net-next/package/nuget/NEST) if you're keen to get your hands on the bleeding edge.

**Comment by neotek** [comment]
Hey @russcam, thanks. We then try as soon as the beta1 is released.

**Comment by thoean** [comment]
I'd like to have clarification on [Removal of mapping types](https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html). While the documentation on the ElasticSearch side is clear, it's unclear for NEST.

Specifically, when calling `.Map<Foo>(...).Map<Bar>(...)`, it returns the correct obsolete information. However, it's unclear (a) how to auto-map multiple types into a single index, (b) how to work with joins since parent/child is also obsolete.

(If you have something short-term, that'd be great as well.)

**Comment by Mpdreamz** [comment]
Hi @thoean 

we've written a how to on the new `join` data type and how to use it from `NEST` here:

https://www.elastic.co/guide/en/elasticsearch/client/net-api/master/parent-child-relationships.html

Hope that explains both (a) and (b)

**Comment by thoean** [comment]
@Mpdreamz , that's what I was looking for. The `[Obsolete]` message could contain something like `use InferMappingFor instead of multiple Map statements`. (I know, this isn't technically correct since there are multiple ways on how to create the mapping. I'm mainly highlighting that there are opportunities to discover the solution for how to do mapping correctly.)

**Comment by russcam** [comment]
Thanks for the feedback @thoean 👍 We will also be putting out a blog post and adding additional documentation including breaking changes once 6.x is GA, to help explain how to transition from a previous version of NEST to 6.x

**Comment by Minx-SigEp** [comment]
Should methods `Nest.TypeMappingDescriptor<T>.Analyzer` and `Nest.TypeMappingDescriptor<T>.SearchAnalyzer` be removed? The ObsoleteAttribute say they are scheduled to be removed in 6.0. Also I think this feature was removed in ES 2 (https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_mapping_changes.html#_analyzer_mappings)

**Comment by Mpdreamz** [comment]
The obsoletes that we currently have are for default analyzer settings at the type level for mapping that have been been removed.

Which indeed have been removed 

> The index_analyzer, search_analyzer, and analyzer type-level settings have also been removed, as it is no longer possible to select fields based on the type name.

We kept them around in `5.x` as they could still be returned from `2.x` indices to aid migration. 

We will remove this from our 6.0 GA releases, doing a final Obsolete removal is still part of this GA checklist.

Thanks for raising this @Minx-SigEp if you see others please feel free to raise them here again.

**Comment by codebrain** [comment]
Thanks @Minx-SigEp - PR open with code to be removed in NEST 6:
https://github.com/elastic/elasticsearch-net/pull/3067

**Comment by Mpdreamz** [comment]
The GA release is up on NuGet 

- [ ] generate binary changes documentation on elastic.co (now that we have a `6.x` branch, still needs to wait for that internally to be merged and published).
- [ ] Published staged blogpost
- [ ] Add some release notes here: https://github.com/elastic/elasticsearch-net/releases/tag/6.0.0 does not need to be extensive and can link to the blog post.
- [ ] Tweet

**Comment by russcam** [comment]
I've added 6.x and the breaking changes for it to the docs. I think we can improve the layout of the asciidoc breaking changes to make them clearer. Going to look at this

**Comment by russcam** [comment]
[Added release notes for 6.0](https://github.com/elastic/elasticsearch-net/releases/tag/6.0.0)

**Comment by ghavaun** [comment]
How to fix this please

**Comment by russcam** [comment]
@ghavaun  it's not clear what you're asking to fix. If there's an issue, please open a new issue and describe what it is.
