### ISSUE TITLE
6.3.0 release 

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#3386]
Release 6.3 checklist 

## Pending PR's

- [x]  Long range query support #3299

## Forward port to master

- [x] fix #3326 Add index_prefixes to Text property mapping (#3362) a3d2005
- [x] Fix #3327 Add span_gap query for use with span_near query (#3361) d215520
- [x] Fix #3328 Add periodic flush count to FlushStats (#3360)  … 524f141
- [x] Fix #3325 Add support for zero_terms_query to match_phrase query (#3363) 93400ac
- [x] Fix #3323 Add support for null_value, ignore_z_value on GeoPoint prop… ( … 9c7e599
- [x] Fix #3318 Support 3rd dimension (Z value) to points for geo_point and… ( … 5cc9a51
- [x] Fix #3330 Add additional translog properties as per elastic/elasticse… … 7ff63ab
- [x] Fix #3317 and #3322 add after_key support to composite aggregation re… ( … 69775d6
- [x] Fix #3315 obsolete the update_all_types querystring parameter (#3368) 4250901
- [x] Fix #3316 allow generated enum members to be obsoleted (#3369) 6007a70
- [x] Fix #3320 Add Painless script execute API (#3370)  … bcdc1d6
- [x] Feature/node stats 6.3 (#3359)  … 7e42dea
- [x] Add MatchPattern to dynamic templates (#3374)  … 1c26ece
- [x] Include Result property on IBulkResponseItem (#3376)  … 5bf170d
- [ ] Add support for geo_shape represented as Well-Known Text (WKT) (#3377) … 017d8b6
- [x] Add note about filter_path and deserialization (#3379)  … 0f6aac0
- [x] Add include_aliases and partial to Snapshot Restore request (#3380)  … 0afe4fd
- [x] Support Ids in MultiTermVectors API (#3382)  … 491a4a4
- [x] Include LatLongDetector on DetectorsDescriptor<T> (#3384)  … e46c70d
- [x] bump Elastic abstractions, StartAsyncReads was called on dispose even… … 75a70a4
- [x] Bump Elastic.Xunit and make sure we emit output after node started, c… … 2311bdb
- [x] Expect Json used Id which tripped canary builds testing against the n… … 3848aee
- [ ] GeoWKT test depending on source line endings: https://github.com/elastic/elasticsearch-net/commit/0d0afdbbcfa00f8aa9337cd25bd324b4e314730b
- [x] 164583b4e Move LongRangeQuery tests into split Test projects
- [x] 69733eac9 Long range query support (#3299)
- [x] 1230f1c24 TextPropertyTests uses a 6.3.0 only  feature so needs a SkipVersion attribute
- [x] 200106dd2 Ingest stats not always avaialable
- [x] 02f34fff0 Make sure MaximumResponseHeadersLength is not set when using WebRequestConnection on core
- [x] e6eb8dcfc DefaultSeeder should not set cluster.routing.use_adaptive_replica_selection on 6.x versions
## Post 6.3 merge.

- [ ] Rebase `6.4` against `6.x`
- [x] Make sure docs are up to date on the `6.x` branch (`build.bat`)

## Preparing release 

- [x] Verify `6.x` is green on all integration tracks.
  - [x] 6.0.1
  - [x] 6.1.4
  - [x] 6.2.4
  - [x] 6.3.0
- [x] Run diff with `6.2.0` nuget package and make sure there are no breaking changes (`build.bat diff nuget 6.2.0 dir .`)
- [x] Produce artifacts and release notes. `build.bat release 6.3.0`
- [x] Commit and push bumped version numbers on `6.x`
- [x] Tag bump commit `git tag -a 6.3.0 -m 6.3.0`
- [x] `git push --tags`
- [x] Create release on Github from the tag
- [x] Push to nuget.org
- [x] Tweet 🐦

**Comment by Mpdreamz** [comment]
* [Nest.txt](https://github.com/elastic/elasticsearch-net/files/2367203/Nest.txt) diff with `NEST 6.2.0` on nuget
* [Elasticsearch.Net.txt](https://github.com/elastic/elasticsearch-net/files/2367220/Elasticsearch.Net.txt) diff with `Elasticsearch 6.2.0` on nuget.

The latter has `Deleted` markers for `HttpConnection` but these are still there although now on a subclass.

**Comment by Mpdreamz** [comment]
@codebrain @russcam https://github.com/elastic/elasticsearch-net/commit/112d59798eb230bf58aa121e1263c4485a41e29f  is ready to cut a `6.3.0` from. Can you give this a quick look over/sanity check before I release tomorrow?


## Release notes
------

https://github.com/elastic/elasticsearch-net/compare/6.3.0...6.3.0

## Uncategorized

- #3331 Warn FilterPath transforms the response and can break response parsing
- #3357 Correctly deserialize JoinField
- #3358 Fix #3330 Add additional translog properties as per elastic/elasticsearch#28613…
- #3359 Feature/node stats 6.3
- #3360 Fix #3328 Add periodic flush count to FlushStats
- #3361 Fix #3327 Add span_gap query for use with span_near query
- #3362 fix #3326 Add index_prefixes to Text property mapping
- #3363 Fix #3325 Add support for zero_terms_query to match_phrase query
- #3364 Fix #3323 Add support for null_value, ignore_z_value on GeoPoint prop…
- #3365 Fix #3318 Support 3rd dimension (Z value) to points for geo_point and…
- #3367 Fix #3317 and #3322 add after_key support to composite aggregation re…
- #3368 Fix #3315 obsolete the update_all_types querystring parameter
- #3369 Fix #3316 allow generated enum members to be obsoleted
- #3370 Fix #3320 Add Painless script execute API
- #3373 No Nest support for DynamicTemplate.MatchPattern (match_pattern property)
- #3383 Include LatLongDetector on DetectorsDescriptor<T>
- #3391 Obsolete HttpWebRequestConnection on .NET Core
- #3393 Update TypeNameResolver.cs
- #3394 scripts is now an SDK style project as well that is part of the solut…
- #3396 Previous commits removed parent_node which needs to be obsoleted for …

## Features & Enhancements

- #3219 How to use the MultiTermVectorsAsync API
- #3256 Add WKT Support to Geo
- #3299 Long range query support
- #3317 Add date format to DateHistogram source for Composite Aggregation
- #3318 Support 3rd dimension (Z value) to points for geo_point and points in geo_shapes
- #3320 Add Painles script execute API
- #3321 Add support for `allow_partial_search_results` search request parameter
- #3322 Add after_key to CompositeAggregation response
- #3323 Add support for null_value on GeoPoint property
- #3324 Add acknowledge request parameter to Start Trial API
- #3325 Add support for zero_terms_query to match_phrase query
- #3326 Add index_prefixes to Text property mapping
- #3327 Add span_gap query for use with span_near query
- #3328 Add periodic flush count to FlushStats
- #3329 Add Adaptive selection statistics to NodeStats
- #3330 Add Translog files age to TranslogStats
- #3340 Include include_aliases in Snapshot Restore request
- #3375 IBulkResponseItem does not contain a Result property

## Deprecations

- #3315 Deprecate update_all_types parameter
- #3316 Deprecate suggest enum member on NodesStatsIndexMetric

### [View the full list of issues and PRs](https://github.com/elastic/elasticsearch-net/issues?utf8=%E2%9C%93&q=label%3Av6.3.0)

**Comment by codebrain** [comment]
@Mpdreamz - have reviewed and updated the original text ^

**Comment by russcam** [comment]
There are a few important notes I think we should highlight at the top of the release notes:

1. .NET 4.5 support was removed in NEST 6.2.0, but the nuspec definition had residual group dependencies in it, which have now been removed. Users using .NET 4.5 should look to move to .NET 4.6.1.
2. .NET 4.6 support has been bumped to .NET 4.6.1
3. .NET Standard 1.3 support has been bumped to .NET Standard 2.0

The rest of the list LGTM @Mpdreamz 👍

**Comment by Mpdreamz** [comment]
Thanks guys! `6.3.0` is live:

* Release notes: https://github.com/elastic/elasticsearch-net/releases/tag/6.3.0
* Tweet: https://twitter.com/Mpdreamz/status/1039436088836874241
