### ISSUE TITLE
[meta] 6.5.0 Release

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#3457]
This is a meta issue to keep track of the work we want to do for the `6.4.0` release [individual tickets with the v6.4.0 tag will be created for most of these](https://github.com/elastic/elasticsearch-net/issues?q=is%3Aissue+is%3Aopen+label%3Av6.4.0).

#### 6.4.0 leftover work
- [x] Add Kerberos authentication support - https://github.com/elastic/elasticsearch/pull/32263 
- [ ] ML. Detectors now support custom rules that enable the user to improve machine learning results by providing some domain-specific knowledge in the form of rule. - https://github.com/elastic/elasticsearch/issues/31110
- [ ] ML. Reverse engineer Grok patterns from categorization results - https://github.com/elastic/elasticsearch/pull/30125
- [x] Add a format option to docvalue_fields. - https://github.com/elastic/elasticsearch/pull/29639

#### 6.4.0 leftover work
- [ ] Return statistics about forecasts as part of the job stats and usage API - https://github.com/elastic/elasticsearch/pull/31647
- [ ] [ML] Add description to ML filters - https://github.com/elastic/elasticsearch/pull/31330
- [ ] Rename ranking evaluation quality_level to metric_score - https://github.com/elastic/elasticsearch/pull/32168
- [ ] Rename ranking evaluation response unknown_docs section - https://github.com/elastic/elasticsearch/pull/32166
- [ ] Add Expected Reciprocal Rank metric - https://github.com/elastic/elasticsearch/pull/31891
- [ ] Add details section for dcg ranking metric - https://github.com/elastic/elasticsearch/pull/31177

#### 6.4.0 leftover work
- [x] xpack.license.get_basic_status.json
- [x] xpack.license.post_start_basic.json
- [ ] xpack.ml.delete_calendar.json
- [ ] xpack.ml.delete_calendar_event.json
- [ ] xpack.ml.delete_calendar_job.json
- [ ] xpack.ml.get_calendar_events.json
- [ ] xpack.ml.get_calendars.json
- [ ] xpack.ml.info.json
- [ ] xpack.ml.post_calendar_events.json
- [ ] xpack.ml.put_calendar.json
- [ ] xpack.ml.put_calendar_job.json
- [ ] xpack.ml.get_calendar_job.json
- [x] xpack.ssl.certificates.json 
- [ ] xpack.ml.update_filter.json
- [x] xpack.rollup.get_rollup_index_caps.json
- [ ] xpack.security.delete_privileges.json
- [ ] xpack.security.get_privileges.json
- [ ] xpack.security.has_privileges.json
- [ ] xpack.security.put_privilege.json
- [ ] xpack.security.put_privileges.json
- [x] nodes.reload_secure_settings.json

#### 6.5.0 new API

- [ ] delete_by_query_rethrottle.json
- [ ] update_by_query_rethrottle.json
- [ ] xpack.ml.delete_forecast.json
- [ ] xpack.ml.find.file_structure.json
- [ ] xpack.security.get_user_privileges.json
- [x] ccr.delete_auto_follow_pattern.json
- [x] ccr.follow.json
- [x] ccr.follow_stats.json
- [x] ccr.get_auto_follow_pattern.json
- [x] ccr.pause_follow.json
- [x] ccr.put_auto_follow_pattern.json
- [x] ccr.resume_follow.json
- [x] ccr.stats.json
- [x] ccr.unfollow.json

## From the release notes:

- [x] Handles exists query in composite aggs elastic/elasticsearch#35758
- [x] [Scripting] Use Number as a return value for BucketAggregationScript elastic/elasticsearch#35653
- [x] Require combine and reduce scripts in scripted metrics aggregation elastic/elasticsearch#33452
- [x] Disallow "enabled" attribute change for types in mapping update (elastic/elasticsearch#33566) elastic/elasticsearch#33933
- [x] Introduce index store plugins elastic/elasticsearch#32375
- [x] Deprecates the standard filter elastic/elasticsearch#33468
- [x] Deprecate negative query boost (elastic/elasticsearch#34486) elastic/elasticsearch#34512
- [x] Deprecate negative `weight` in Function Score Query elastic/elasticsearch#33624
- [x] Switch WritePipelineResponse to AcknowledgedResponse elastic/elasticsearch#32722
- [x] Adds a new auto-interval date histogram elastic/elasticsearch#28993
- [x] Add script_filter tokenfilter elastic/elasticsearch#33431
- [x] Add conditional token filter to elasticsearch elastic/elasticsearch#31958
- [ ] Add get-user-privileges API elastic/elasticsearch#33928
- [x] Add support for "authorization_realms" elastic/elasticsearch#33262
- [x] [CCR] Added auto follow patterns feature elastic/elasticsearch#33118
- [ ] Rollup adding support for date field metrics (elastic/elasticsearch#34185) elastic/elasticsearch#34200
- [x] Add early termination support for min/max aggregations elastic/elasticsearch#33375
- [x] Add early termination support to BucketCollector elastic/elasticsearch#33279
- [x] Add interval response parameter to AutoDateInterval histogram elastic/elasticsearch#33254
- [x] Token API supports the client_credentials grant elastic/elasticsearch#33106
- [x] Improved IndexNotFoundException's default error message elastic/elasticsearch#34649
- [ ] Introduce index settings version elastic/elasticsearch#34429
- [ ] Introduce mapping version to index metadata elastic/elasticsearch#33147
- [x] ingest: processor stats elastic/elasticsearch#34724
- [x] ingest: better support for conditionals with simulate?verbose elastic/elasticsearch#34155
- [x] ingest: correctly measure chained pipeline stats elastic/elasticsearch#33912
- [x] ingest: support simulate with verbose for pipeline processor elastic/elasticsearch#33839
- [x] ingest: Introduce the dissect processor elastic/elasticsearch#32884
- [x] [ingest] geo-ip performance improvements elastic/elasticsearch#33029
- [x] INGEST: Add Pipeline Processor elastic/elasticsearch#32473
- [x] Ingest: Add conditional per processor elastic/elasticsearch#32398
- [x] Introduce the dissect library elastic/elasticsearch#32297
- [x] INGEST: Enable default pipelines elastic/elasticsearch#32286
- [x] INGEST: Implement Drop Processor elastic/elasticsearch#32278
- [x] Ingest: Support integer and long hex values in convert elastic/elasticsearch#32213
- [x] Add region ISO code to GeoIP Ingest plugin elastic/elasticsearch#31669
- [x] [ML] Add an ingest pipeline definition to structure finder elastic/elasticsearch#34350
- [ ] [ML] Add a timeout option to file structure finder elastic/elasticsearch#34117
- [ ] [ML] Allow asynchronous job deletion elastic/elasticsearch#34058
- [ ] Make certain ML node settings dynamic (elastic/elasticsearch#33565) elastic/elasticsearch#33961
- [ ] Adding node_count to ML Usage (elastic/elasticsearch#33850) elastic/elasticsearch#33863
- [ ] [ML] Minor improvements to categorization Grok pattern creation elastic/elasticsearch#33353
- [x] Preserve the order of nested documents in the Lucene index elastic/elasticsearch#34225
- [ ] [ML] Delete forecast API (elastic/elasticsearch#31134) elastic/elasticsearch#33218
- [x] Use the global doc id to generate random scores elastic/elasticsearch#33599
- [x] Add minimal sanity checks to custom/scripted similarities. (backport) elastic/elasticsearch#33893
- [x] Propagate auto_id_timestamp in primary-replica resync elastic/elasticsearch#33964
- [ ] [Rollup] Add support for date histo `format` when searching elastic/elasticsearch#34537
- [ ] [Rollup] Only allow aggregating on multiples of configured interval elastic/elasticsearch#32052
- [x] Introduce a `search_throttled` threadpool elastic/elasticsearch#33732
- [x] Expose `max_concurrent_shard_requests` in `_msearch` elastic/elasticsearch#33016
- [x] Add a limit for graph phrase query expansion elastic/elasticsearch#34031
- [x] Introduce private settings elastic/elasticsearch#33327
- [x] Add user-defined cluster metadata elastic/elasticsearch#33325
- [x] Add `_source`-only snapshot repository elastic/elasticsearch#32844
- [x] Make XContentBuilder in AliasActions build `is_write_index` field elastic/elasticsearch#35071

## Netcoreapp2.1

or 2.2 whichever comes first ðŸ˜¸. 

- [ ] Explicitly ship this TFM and get some numbers how the managed handler performs on linux/windows through `Tests.Throughput` vs the already existing implementations/
- [ ] Move our dotnet core `IHttpConnection` over to `HttpClientFactory`. We currently do much of the same but if we don't have to maintain our own pooling of `HttpClient` instances that would eleviate some complexity in our codebase.
- [ ] Span based JSON serializer implementation?

## Elasticsearch.Net.Abstractions

- [x] Use differ from this repository see: https://github.com/elastic/elasticsearch-net-abstractions/pull/13
- [ ] Move `ApiGeneration` over.
- [ ] Move `DocGeneration` over.

**Comment by Mpdreamz** [comment]
Differ is now using the differ we release from: https://github.com/nullean/AssemblyDiffer

https://github.com/elastic/elasticsearch-net/blob/master/build/scripts/Targets.fsx#L68-L73

**Comment by Mpdreamz** [comment]
Document kerberos integration: https://github.com/elastic/elasticsearch-net/pull/3519

**Comment by Mpdreamz** [comment]
Format for `doc_values` fields already went out the door with https://github.com/elastic/elasticsearch-net/pull/3491

**Comment by Mpdreamz** [comment]
#3520 => Deprecates the standard filter elastic/elasticsearch#33468

**Comment by Mpdreamz** [comment]
[Diff.zip](https://github.com/elastic/elasticsearch-net/files/2802547/Diff.zip)

Attached is the output for AssemblyDiffer for NEST and Elasticsearch.net against 6.4.2 as released on Nuget.

LGTM could use extra pair of eyes to validate @russcam @codebrain

**Comment by Mpdreamz** [comment]
Moved open bullet points over to https://github.com/elastic/elasticsearch-net/issues/3552

**Comment by codebrain** [comment]
@Mpdreamz - checked both XMLs, they look good.
