### ISSUE TITLE
[meta] 6.6.0 Release

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#3552]
# Leftover Work

### New Features 6.5.0

- [x] ML. Reverse engineer Grok patterns from categorization results - https://github.com/elastic/elasticsearch/pull/30125 - *skipped as marked experimental*

### Enhancements 6.5.0
- [x] Add keywords_pattern to Keyword Marker Token Filter. https://github.com/elastic/elasticsearch-net/pull/3558
- [x] Return statistics about forecasts as part of the job stats and usage API - https://github.com/elastic/elasticsearch/pull/31647 https://github.com/elastic/elasticsearch-net/pull/3593
- [x] [ML] Add description to ML filters - https://github.com/elastic/elasticsearch/pull/31330 - *skipped as filters are marked experimental*
- [x] Rename ranking evaluation quality_level to metric_score - https://github.com/elastic/elasticsearch/pull/32168  - *skipped as `rank_eval` is marked experimental and not implemented yet*
- [x] Rename ranking evaluation response unknown_docs section - https://github.com/elastic/elasticsearch/pull/32166- *skipped as `rank_eval` is marked experimental and not implemented yet*
- [x] Add Expected Reciprocal Rank metric - https://github.com/elastic/elasticsearch/pull/31891- *skipped as `rank_eval` is marked experimental and not implemented yet*
- [x] Add details section for dcg ranking metric - https://github.com/elastic/elasticsearch/pull/31177- *skipped as `rank_eval` is marked experimental and not implemented yet*
- [x] [ML] Add a timeout option to file structure finder elastic/elasticsearch#34117 - *skipped as marked experimental*
- [x] [ML] Allow asynchronous job deletion elastic/elasticsearch#34058
- [x] Make certain ML node settings dynamic (elastic/elasticsearch#33565) elastic/elasticsearch#33961 - *no change needed, API not affected*
- [x] Adding node_count to ML Usage (elastic/elasticsearch#33850) elastic/elasticsearch#33863 - https://github.com/elastic/elasticsearch-net/pull/3603 
- [x] [ML] Minor improvements to categorization Grok pattern creation elastic/elasticsearch#33353 - *does not affect REST API*
- [x] [ML] Delete forecast API (elastic/elasticsearch#31134) elastic/elasticsearch#33218 - https://github.com/elastic/elasticsearch-net/pull/3591
- [x] [Rollup] Add support for date histo `format` when searching elastic/elasticsearch#34537 - https://github.com/elastic/elasticsearch-net/pull/3594
- [x] [Rollup] Only allow aggregating on multiples of configured interval elastic/elasticsearch#32052 - *internal ES change, no API changes required*

### New API's 6.4.0 

- [x] xpack.ml.delete_calendar.json - https://github.com/elastic/elasticsearch-net/pull/3569
- [x] xpack.ml.delete_calendar_event.json - https://github.com/elastic/elasticsearch-net/pull/3569
- [x] xpack.ml.delete_calendar_job.json - https://github.com/elastic/elasticsearch-net/pull/3569
- [x] xpack.ml.get_calendar_events.json - https://github.com/elastic/elasticsearch-net/pull/3569
- [x] xpack.ml.get_calendars.json - https://github.com/elastic/elasticsearch-net/pull/3569
- [x] xpack.ml.post_calendar_events.json - https://github.com/elastic/elasticsearch-net/pull/3569
- [x] xpack.ml.put_calendar.json - https://github.com/elastic/elasticsearch-net/pull/3569
- [x] xpack.ml.put_calendar_job.json - https://github.com/elastic/elasticsearch-net/pull/3569
- [x] xpack.ml.get_calendar_job.json - https://github.com/elastic/elasticsearch-net/pull/3569
- [x] xpack.ml.update_filter.json - *experimental, do not implement*
- [x] xpack.ml.info.json - https://github.com/elastic/elasticsearch-net/pull/3571
- [x] xpack.security.delete_privileges.json - https://github.com/elastic/elasticsearch-net/pull/3584
- [x] xpack.security.get_privileges.json - https://github.com/elastic/elasticsearch-net/pull/3584
- [x] xpack.security.has_privileges.json - https://github.com/elastic/elasticsearch-net/pull/3584
- [x] xpack.security.put_privilege.json - https://github.com/elastic/elasticsearch-net/pull/3584
- [x] xpack.security.put_privileges.json - https://github.com/elastic/elasticsearch-net/pull/3584

#### New API's 6.5.0 

- [x] delete_by_query_rethrottle.json (@russcam )
- [x] update_by_query_rethrottle.json (@russcam)
- [x] xpack.ml.delete_forecast.json - https://github.com/elastic/elasticsearch-net/pull/3591
- [x] xpack.ml.find.file_structure.json - *experimental, do not implement*
- [x] xpack.security.get_user_privileges.json - https://github.com/elastic/elasticsearch-net/pull/3584

# 6.6.0

#### Ranking:
- [x] Forbid negative scores in function_score query elastic/elasticsearch#35709 (issue: elastic/elasticsearch#33309) - *This shouldn't require any changes to the client*

#### Search:
- [x] Throw a parsing exception when boost is set in span_or query elastic/elasticsearch#28390 elastic/elasticsearch#34112 (issue: elastic/elasticsearch#28390)

#### Watcher:
- [x] Fix metric stats names elastic/elasticsearch#34951 (issue: elastic/elasticsearch#34865) - *fixed in new `xpack.watcher.stats.json` json spec*

#### Aggregations:
- [x] Deprecate dots in aggregation names elastic/elasticsearch#31468 (issues: elastic/elasticsearch#17600, elastic/elasticsearch#19040) - *This shouldn't require any changes to the client*

#### Core:
- [x] Deprecate use of scientific notation in epoch time parsing elastic/elasticsearch#36691 - *This shouldn't require any changes to the client*

#### Search:
- [x] Deprecate the _termvector endpoint. elastic/elasticsearch#36098 (issue: elastic/elasticsearch#8484) - *endpoint regeneration has resolved this*
- [x] Deprecate `_source_include` and `_source_exclude` url parameters elastic/elasticsearch#33475 (issue: elastic/elasticsearch#22792) - *endpoint regeneration has solved this*

#### Security::
- [x] Undeprecate /_license endpoints elastic/elasticsearch#35974 (issue: elastic/elasticsearch#35959) - *no client changes required*

#### Watcher::
- [x] Undeprecate /_watcher endpoints elastic/elasticsearch#36269 - *no client changes required*

### Aggregations
- [x] Refactor children aggregator into a generic ParentJoinAggregator #34845 (issue: #34210)
- [x] Add parent-aggregation to parent-join module #34210 (issue: #9705)

**Comment by vohanka** [comment]
Hello,
may I ask if you are going to solve these issues 

> Refactor children aggregator into a generic ParentJoinAggregator #34845 (issue: #34210)

>  Add parent-aggregation to parent-join module #34210 (issue: #9705)

in near future? 

Thank you very much for your answer.

Libor.

**Comment by russcam** [comment]
@vohanka I've opened #3609 to address in the next release

**Comment by vohanka** [comment]
Hello @codebrain and @russcam - great work, thank you very much.

**Comment by vohanka** [comment]
Thank you for support works great.

**Comment by codebrain** [comment]
Superceded by https://github.com/elastic/elasticsearch-net/issues/3615
