### ISSUE TITLE
[meta] 6.7.0 Release

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#3615]
# Leftover Work

### New Features 6.5.0
- [x] ML. Detectors now support custom rules that enable the user to improve machine learning results by providing some domain-specific knowledge in the form of rule. - https://github.com/elastic/elasticsearch/issues/31110 (@russcam)

# 6.6.0

#### Cross-cluster replication:
- [x] Change get autofollow patterns API response format elastic/elasticsearch#3620 (issue: elastic/elasticsearch#36049) - *breaking change in minor - implement custom json convertor on deserialize* (@codebrain)

#### Aggregations
- [x] Median absolute deviation agg elastic/elasticsearch#34482 (issue: elastic/elasticsearch#26681)

#### Analysis:
- [x] Add support for inlined user dictionary in Nori elastic/elasticsearch#36123 (issue: elastic/elasticsearch#35842) (@russcam)
- [x] Add a prebuilt ICU Analyzer elastic/elasticsearch#34958 (issue: elastic/elasticsearch#34285) (@russcam)

#### Index Lifecycle Management:
- [x] Adds Index lifecycle feature elastic/elasticsearch#35193 - (see ilm* endpoints: https://github.com/elastic/elasticsearch/tree/master/x-pack/plugin/src/test/resources/rest-api-spec/api / https://www.elastic.co/guide/en/elasticsearch/reference/6.6/index-lifecycle-management-api.html) @codebrain (https://github.com/elastic/elasticsearch-net/pull/3671)

#### Geo:
- [x] Store job configuration information in the new `.ml-config` index elastic/elasticsearch#36698 (issue: elastic/elasticsearch#32905) - *looks like no impact on client*

#### Search::
- [x] Make lucene's IntervalQuery available via the Query DSL elastic/elasticsearch#32406 (issue: elastic/elasticsearch#29636) - *Use documentation and YML from 7.0 - https://www.elastic.co/guide/en/elasticsearch/reference/7.0/query-dsl-intervals-query.html - https://github.com/elastic/elasticsearch/blob/7.0/rest-api-spec/src/main/resources/rest-api-spec/test/search/230_interval_query.yml*

### Aggregations
- [x] Handles exists query in composite aggs #35758 - *No client implementation needed.*

#### Authentication
- [x] Invalidate Token API enhancements - HLRC #36362 (says HLRC but adds to request/response) - @codebrain (https://github.com/elastic/elasticsearch-net/pull/3684)
- [x] Add realm information for Authenticate API #35648
- [x] Formal support for "password_hash" in Put User #35242 (issue: #34729) - https://github.com/elastic/elasticsearch-net/pull/3723
- [x] Enhance Invalidate Token API #35388 (issues: #34556, #35115)

#### Core
- [x] Added wait_for_metadata_version parameter to cluster state api. #35535

#### Cross-cluster replication
- [x] Add time since last auto follow fetch to auto follow stats #36542 (issues: #33007, #35895)

The last two removed `CCR_AUTO_FOLLOW_POLL_INTERVAL` which i think is returned on the ccr stats API's (investigate)

#### Aggregations::
- [x] Fix MultiValuesSourceFieldConfig toXContent [#36525] (issue: [#36474]) - *no change needed, server side issue*

#### circuit breakers::
- [x] modify `bigarrays` to take name of circuit breaker [#36461] (issue: [#31435])

#### Core::
- [x] Suppress CachedTimeThread in hot threads output [#35558] (issue: [#23175])

#### Cross-cluster replication::
- [x] Add `fatal_exception` field for ccr stats in monitoring mapping [#37563]

#### Geo::
- [x] Enables coerce support in WKT polygon parser [#35414] (issue: [#35059]) - https://github.com/elastic/elasticsearch-net/pull/3718

#### Rollup::
- [x] Fix Rollup's metadata parser [#36791] (issue: [#36726]) - *no client changes needed*

#### Search::
- [x] Inner hits fail to propagate doc-value format. (#36310) [#36355] (issue: [#36310]) - *no client change needed, already in `FieldJsonConverter`*
- [x] Fix custom AUTO issue with Fuzziness#toXContent [#35807] (issue: [#33462]) - *no client change needed, server fix only*

Do we expose doc value format on inner hit?

#### Snapshot/Restore::
- [x] Register Azure max_retries setting [#35286] - *no client change needed*

**Comment by codebrain** [comment]
Superceded by: https://github.com/elastic/elasticsearch-net/issues/3747
