### ISSUE TITLE
[meta] 6.8 release

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#3747]
# Leftover Work

#### Geo:
- [x] Integrate Lucene's LatLonShape (BKD Backed GeoShapes) as default `geo_shape` indexing approach elastic/elasticsearch#35320 (issue: elastic/elasticsearch#32039) - https://github.com/elastic/elasticsearch-net/pull/3770

#### Cross-cluster replication
- [x] Refactor AutoFollowCoordinator to track leader indices per remote cluster #36031 (issues: #33007, #35895) - *no client changes required*
- [x] Refactor auto follow coordinator #35895 (issue: #33007) - *no client changes required*

The last two removed `CCR_AUTO_FOLLOW_POLL_INTERVAL` which i think is returned on the ccr stats API's (investigate)

#### CRUD
- [x] Rename seq# powered optimistic concurrency control parameters to ifSeqNo/ifPrimaryTerm #36757 (issues: #10708, #36148) - no client changes needed, API generator picked up new parameters
- [x] Expose Sequence Number based Optimistic Concurrency Control in the rest layer #36721 (issues: #10708, #36148) - no client changes needed, API generator picked up new parameters
- [x] Add doc’s sequence number + primary term to GetResult and use it for updates #36680 (issues: #10708, #36148) - https://github.com/elastic/elasticsearch-net/pull/3767

#### Distributed
- [x] Add global and index level blocks to IndexSettings #35695 (issues: #35332, #35597) - *no client changes required*

#### Machine Learning
- [x] Enable the use of endpoints starting with `_ml` instead of `_xpack/ml` #36373 (issue: #36315) - *no client changes required*
- [x] Add support for rollup indexes in datafeeds #34654 - *no client changes required*

(First is not actionable on our end in `6.x`).

#### Rollup
- [x] Add non-X-Pack centric rollup endpoints #36383 (issues: #35958, #35962) - no client changes required
- [x] Add more diagnostic stats to job #35471 - https://github.com/elastic/elasticsearch-net/pull/3759
- [x] Add default fields to job configs #34831 - no client changes required
- [x] Add `wait_for_completion` option to StopRollupJob API #34811 (issue: #34574) - no client changes required, was picked up in an API regen

#### Search
- [x] Warn when using use_dis_max in multi_match #36614 (issue: #36488) - no client changes required
- [x] Extend field caps API to mark meta fields #36309 - original issue was closed

#### Security
- [x] Make credentials mandatory when launching xpack/migrate #36197 (issues: #29847, #33972) - no client changes required
- [x] Make credentials mandatory when launching x-pack/migrate #33972 (issue: #29847) - no client changes required

#### SQL
- [x] Move requests' parameters to requests JSON body #36149 (issue: #35992) - no client changes needed
- [x] XPack FeatureSet functionality #35725 (issue: #34821) - https://github.com/elastic/elasticsearch-net/pull/3764

#### Stats
- [x] Handle OS pretty name on old OS without OS release #35453 (issue: #35440)
- [x] Add more detailed OS name on Linux #35352 - https://github.com/elastic/elasticsearch-net/pull/3766

#### Aggregations::
- [x] Preserve `format` when aggregation contains unmapped date fields [#35254] (issue: [#31760]) - reminds me of a ticket we once raised (will follow up to figure if they are related) - no client changes needed, this is a server-side change

#### Cross-cluster replication::
- [x] Resume follow Api should not require a request body [#37217] (issue: [#37022]) (_breaking change we need a patch for) - change was implemented on 10th Jan, but CCR was implement in client on 25th Jan, therefore no client changes needed as already incorporated.
- [x] Report error if auto follower tries auto follow a leader index with soft deletes disabled [#36886] (issue: [#33007]) - no client changes needed
- [x] Fix the names of CCR stats endpoints in usage API [#35438] - no client changes needed

#### Index lifecycle management::
- [x] Remove `indexing_complete` when removing policy [#36620] - no client changes needed

#### Index APIs::
- [x] Make XContentBuilder in AliasActions build `is_write_index` field [#35071] - no client changes needed
- [x] Raise a 404 exception when document source is not found (#33384) [#34083] (issue: [#33384]) - no client changes needed

#### Ingest::
- [x] Support default pipelines + bulk upserts [#36618] (issue: [#36219]) - no client changes needed
- [x] Support default pipeline through an alias [#36231] (issue: [#35817]) - no client changes needed

#### Network::
- [x] Do not resolve addresses in remote connection info [#36671] (issue: [#35658]) - no client changes needed
- [x] Always compress based on the settings [#36522] (issue: [#36399]) - no client changes needed
- [x] http.publish_host should contain CNAME [#32806] (issue: [#22029]) - no client changes needed

#### Scripting::
- [x] Fix serialization bug in painless execute api request [#36075] (issue: [#36050]) - no client changes needed

**Comment by codebrain** [comment]
Linked to: https://github.com/elastic/elasticsearch-net/pull/3770

**Comment by codebrain** [comment]
Relates to: https://github.com/elastic/elasticsearch-net/pull/3774
