### ISSUE TITLE
[meta] 7.1 release

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#3895]
# 7.1

**Docs**
- [x] Update serialisation docs for `7.x` https://www.elastic.co/guide/en/elasticsearch/client/net-api/current/custom-serialization.html#custom-serialization - https://github.com/elastic/elasticsearch-net/issues/3926 - https://github.com/elastic/elasticsearch-net/commit/1ad6768b6da3dfa2b19dc6acdd1f9ec9ad157f1c

**Snapshot/Restore**
- [x] Include size of snapshot in snapshot metadata elastic/elasticsearch#30890 (issue: elastic/elasticsearch#18543) - https://github.com/elastic/elasticsearch-net/pull/3911

**Authentication**
- [x] Add support for API keys to access Elasticsearch elastic/elasticsearch#38291 (issue: elastic/elasticsearch#34383) - https://github.com/elastic/elasticsearch-net/pull/3912

~- [ ] OpenID Connect Realm base functionality elastic/elasticsearch#37009 (issue: elastic/elasticsearch#35339) - https://www.elastic.co/guide/en/elastic-stack-overview/master/_openid_connect_without_kibana.html~ - _bumping to 7.2.0_

**CCR**
- [x] Add ccr follow info api #37408 (issue: #37127) - https://github.com/elastic/elasticsearch-net/pull/3927

**Geo**
- [x] geotile_grid implementation #37842 (issue: #30240) - https://github.com/elastic/elasticsearch-net/pull/3932 

**Machine Learning**
~- [ ] Adds set_upgrade_mode API endpoint #37837 - _check production ready_~ _bump to 7.2.0_
~- [ ] Add upgrade mode docs, hlrc, and fix bug #37942~ _bump to 7.2.0_

**Mapping**
- [x] Expose Lucene’s FeatureField. #30618
- [x] Add nanosecond field mapper #37755 (issues: #27330, #32601) - https://github.com/elastic/elasticsearch-net/pull/3933

**Ranking**
- [x] ~Add ranking evaluation API #27478 (issue: #19195)~ - _still marked as experimental_

**Search**
- [x] ~Add a maximum search request size. #26423~ - _cluster setting, not on request objects_

**Analysis**
- [x] Allow word_delimiter_graph_filter to not adjust internal offsets #36699 (issues: #33710, #34741) - https://github.com/elastic/elasticsearch-net/pull/3934

**Authentication**
- [x] Enhance Invalidate Token API #35388 (issues: #34556, #35115) - https://github.com/elastic/elasticsearch-net/pull/3937

**CCR**
- [x] Introduce forget follower API #39718 (issue: #37165) - https://github.com/elastic/elasticsearch-net/pull/3939

**Engine**
- [x] Add a _freeze / _unfreeze API #35592 (issue: #34352) - https://github.com/elastic/elasticsearch-net/pull/3940

**Features/CAT APIs**
~- [ ] Expose search.throttled on _cat/indices#37073 (issue: #34352)~ _does not require client changes_

---

Also, check the following:

**Aggregations**
- [x] Added keyed response to pipeline percentile aggregations 22302 #36392 (issue: #22302)

~- [ ] Added parent validation for auto date histogram #35670~ _server-side validation, no client changes needed_

~- [ ] Allow nested fields in the composite aggregation #37178 (issue: #28611)~ - _no client changes needed, no restrictions in the client_

**Features/ILM**
- [x] Add set_priority action to ILM #37397 (issue: #36905) - _already implemented in client_
- [x] Add Freeze Action #36910 (issue: #34630) - _already implemented in client_

**Features/Indices APIs**
- [x] Add rollover-creation-date setting to rolled over index #31144 (issue: #30887) - _no client changes needed_

**Comment by russcam** [comment]
Closing this as [NEST 7.1.0 has shipped](https://www.nuget.org/packages/NEST/7.1.0)
