### ISSUE TITLE
[meta] 7.2 Release

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#3980]
# 7.2
### Authentication
 - [x] ~Add an OpenID Connect authentication realm~ [#40674](https://github.com/elastic/elasticsearch/issues/40674) - not implementing in the client as primarily used for Kibana Auth
### Infra/Scripting
 - [x] ~Add a Painless Context REST API~ [#39382](https://github.com/elastic/elasticsearch/issues/39382) - not implementing as API is marked as experimental
### Ranking
 - [x] Expose proximity boosting [#39385](https://github.com/elastic/elasticsearch/pull/39385) (issue: [#33382](https://github.com/elastic/elasticsearch/issues/33382)) - PR open: https://github.com/elastic/elasticsearch-net/pull/3983
 - [x] Add randomScore function in script_score query [#40186](https://github.com/elastic/elasticsearch/pull/40186) (issue: [#31461](https://github.com/elastic/elasticsearch/issues/31461)) - no client changes needed
### SQL
 - [x] Introduce the columnar option for REST requests [#39287](https://github.com/elastic/elasticsearch/pull/39287) (issue: [#37702](https://github.com/elastic/elasticsearch/issues/37702)) - PR open: https://github.com/elastic/elasticsearch-net/pull/3984
### Aggregations
 - [x] Move top-level pipeline aggs out of QuerySearchResult https://github.com/elastic/elasticsearch/issues/40319 (issue: https://github.com/elastic/elasticsearch/issues/40177) - internal server change, no client changes needed
 - [x] Force selection of calendar or fixed intervals in date histo agg [#33727](https://github.com/elastic/elasticsearch/issues/33727) - PR open: https://github.com/elastic/elasticsearch-net/pull/3988
### Authorization
 - [x] Add granular API key privileges https://github.com/elastic/elasticsearch/issues/41488 (issue: https://github.com/elastic/elasticsearch/issues/40031) - no client changes needed, PR was closed,
### CRUD
 - [x] Add details to BulkShardRequest#getDescription() https://github.com/elastic/elasticsearch/issues/41711 - no client changes needed
 - [x] Add version-based validation to reindex requests https://github.com/elastic/elasticsearch/issues/38504 (issue: https://github.com/elastic/elasticsearch/issues/37855) - no client changes needed
### Cluster Coordination
 - [x] Add GET /_cluster/master endpoint https://github.com/elastic/elasticsearch/issues/40047 - no client changes needed
 - [x] Add has_voting_exclusions flag to cluster health output https://github.com/elastic/elasticsearch/issues/38568 - no client changes needed
### Engine
 - [x] Return cached segments stats if include_unloaded_segments is true https://github.com/elastic/elasticsearch/issues/39698 (issue: https://github.com/elastic/elasticsearch/issues/39512) - parameters picked up by API generator
 - [x] Expose external refreshes through the stats API https://github.com/elastic/elasticsearch/issues/38643 (issue: https://github.com/elastic/elasticsearch/issues/36712) - PR open: https://github.com/elastic/elasticsearch-net/pull/3992
### Features/CAT APIs
 - [x] Add start and stop time to cat recovery API https://github.com/elastic/elasticsearch/issues/40378 - not visible to users, therefore no client changes needed
 - [x] Return 0 for negative "free" and "total" memory reported by the OS https://github.com/elastic/elasticsearch/issues/42725 (issue: https://github.com/elastic/elasticsearch/issues/42157) - no client changes needed
### Features/Indices APIs
 - [x] Introduce aliases version https://github.com/elastic/elasticsearch/issues/41397 (issue: https://github.com/elastic/elasticsearch/issues/41396) - no client changes needed
### Features/Java High Level REST Client
 - [x] Added param ignore_throttled=false when indicesOptions.ignoreThrottle… https://github.com/elastic/elasticsearch/issues/42393 (issue: https://github.com/elastic/elasticsearch/issues/42358) - no .NET client changes needed
### Features/Monitoring
 - [x] Add packaging to cluster stats response https://github.com/elastic/elasticsearch/issues/41048 (issue: https://github.com/elastic/elasticsearch/issues/39378) - PR open: https://github.com/elastic/elasticsearch-net/pull/3995
### Machine Learning
 - [x] Add created_by info to usage stats https://github.com/elastic/elasticsearch/issues/40518 (issue: https://github.com/elastic/elasticsearch/issues/38403) - https://github.com/elastic/elasticsearch-net/pull/3996
 - [x] Data frame transforms config HLRC objects https://github.com/elastic/elasticsearch/issues/39691 - no client changes needed
 - [x] Add _preview endpoint https://github.com/elastic/elasticsearch/issues/38924 - not implementing as Dataframes not marked as Stable.
 - [x] Increase maximum forecast interval from 8 weeks to a limit based on the amount of data seen, up to a maximum of 10 years https://github.com/elastic/elasticsearch/issues/214 and https://github.com/elastic/elasticsearch/issues/41082 (issue: https://github.com/elastic/elasticsearch/issues/41103) - no client changes needed
### Mapping
 - [x] Updates max dimensions for sparse_vector and dense_vector to 1024. https://github.com/elastic/elasticsearch/issues/40597 (issue: https://github.com/elastic/elasticsearch/issues/40492) - no client changes needed
### Search
 - [x] Add date and date_nanos conversion to the numeric_type sort option https://github.com/elastic/elasticsearch/issues/40199 - PR open: https://github.com/elastic/elasticsearch-net/pull/3998
 - [x] Add use_field option to intervals query https://github.com/elastic/elasticsearch/issues/40157
### Snapshot/Restore
 - [x] Support multiple repositories in get snapshot request https://github.com/elastic/elasticsearch/issues/41799 (issue: https://github.com/elastic/elasticsearch/issues/41210) - no client changes needed, was bumped to 8.0
 - [x] Add Bulk Delete Api to BlobStore https://github.com/elastic/elasticsearch/issues/40322 (issues: https://github.com/elastic/elasticsearch/issues/40144, https://github.com/elastic/elasticsearch/issues/40250) - no client changes needed
 - [x] Async Snapshot Repository Deletes https://github.com/elastic/elasticsearch/issues/40144 (issues: https://github.com/elastic/elasticsearch/issues/39656, https://github.com/elastic/elasticsearch/issues/39657) - no client changes needed
### Aggregations
 - [x] Fix FiltersAggregation NPE when filters is empty https://github.com/elastic/elasticsearch/issues/41459 (issue: https://github.com/elastic/elasticsearch/issues/41408) - server-side validation only, no client changes needed
### Authentication
 - [x] Fix settings prefix for realm truststore password https://github.com/elastic/elasticsearch/issues/42336 (issues: https://github.com/elastic/elasticsearch/issues/30241, https://github.com/elastic/elasticsearch/issues/41663) - no client changes needed
 - [x] Merge claims from userinfo and ID Token correctly https://github.com/elastic/elasticsearch/issues/42277 - no client changes needed
### Authorization
 - [x] _cat/indices with Security, hide names when wildcard https://github.com/elastic/elasticsearch/issues/38824 (issue: https://github.com/elastic/elasticsearch/issues/37190) - no client changes needed
### Reindex
 - [x] Propogate version in reindex from remote search https://github.com/elastic/elasticsearch/issues/42412 (issue: https://github.com/elastic/elasticsearch/issues/31908) - no client changes needed
### Search
 - [x] Fix sorting on nested field with unmapped https://github.com/elastic/elasticsearch/issues/42451 (issue: https://github.com/elastic/elasticsearch/issues/33644)
more_like_this query to throw an error if the like fields is not provided https://github.com/elastic/elasticsearch/issues/40632 - no client changes needed
# 7.2.1
### Features/CAT APIs
 - [x] Fix indices shown in _cat/indices https://github.com/elastic/elasticsearch/issues/43286 (issues: https://github.com/elastic/elasticsearch/issues/33888, https://github.com/elastic/elasticsearch/issues/38824, https://github.com/elastic/elasticsearch/issues/39933) - no client changes needed
### Mapping
 - [x] Add include_type_name in indices.exitst REST API spec https://github.com/elastic/elasticsearch/issues/43910 (issue: https://github.com/elastic/elasticsearch/issues/43905) - PR was closed, no client changes needed

**Comment by sladeos** [comment]
FYI. All of the links result in a 404 for me. Seems they should use "/issues/" instead of "/issue/"

**Comment by Mpdreamz** [comment]
I think the following have  no impact:

- Add Bulk Delete Api to BlobStore elastic/elasticsearch#40322 (issues: elastic/elasticsearch#40144, elastic/elasticsearch#40250)
- Async Snapshot Repository Deletes elastic/elasticsearch#40144 (issues: elastic/elasticsearch#39656, elastic/elasticsearch#39657)

**Comment by codebrain** [comment]
`7.2.0` was released: https://github.com/elastic/elasticsearch-net/releases/tag/7.2.0
