### ISSUE TITLE
[meta] 7.3 Release

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#4001]
#### Data Frame
~- [x ] Removing format support in date_histogram group_by http://github.com/elastic/elasticsearch/pull/43659~ Data Frame APIs not implemented

#### Features/Java High Level REST Client
~- [x] Deprecate native code info in xpack info api http://github.com/elastic/elasticsearch/pull/43297~ N/A

#### Mapping
~- [x] Deprecate support for chained multi-fields. http://github.com/elastic/elasticsearch/pull/41926 (issue: http://github.com/elastic/elasticsearch/issues/41267)~ no change needed

#### Search
- [x] Deprecate CommonTermsQuery and cutoff_frequency http://github.com/elastic/elasticsearch/pull/42619 (issue: http://github.com/elastic/elasticsearch/issues/37096)

#### Aggregations
- [x] Adds a minimum interval to `auto_date_histogram`. http://github.com/elastic/elasticsearch/pull/42814 (issue: http://github.com/elastic/elasticsearch/issues/41757)
- [x] Add RareTerms aggregation http://github.com/elastic/elasticsearch/pull/35718 (issue: http://github.com/elastic/elasticsearch/issues/20586)

#### Data Frame
~- [x] Add sync api http://github.com/elastic/elasticsearch/pull/41800~ Data Frame APIs not implemented

#### Machine Learning
~- [x] Machine learning data frame analytics http://github.com/elastic/elasticsearch/pull/43544~ Data Frame APIs not implemented 

#### Mapping
- [x] Add support for 'flattened object' fields. http://github.com/elastic/elasticsearch/pull/42541 (issues: http://github.com/elastic/elasticsearch/issues/25312, http://github.com/elastic/elasticsearch/issues/33003)

#### Ranking
~- [x] Move dense_vector and sparse_vector to module http://github.com/elastic/elasticsearch/pull/43280~ N/A

#### Search
- [x] Wildcard intervals http://github.com/elastic/elasticsearch/pull/43691 (issue: http://github.com/elastic/elasticsearch/issues/43198)
- [x] Add prefix intervals source http://github.com/elastic/elasticsearch/pull/43635 (issue: http://github.com/elastic/elasticsearch/issues/43198)
~- [x] Add an option to force the numeric type of a field sort http://github.com/elastic/elasticsearch/pull/38095 (issue: http://github.com/elastic/elasticsearch/issues/32601)~ [Went into Elasticsearch v7.2.0](https://github.com/elastic/elasticsearch/blob/be513ce15956f552792fdfe0d661ee65b163dd67/server/src/main/java/org/elasticsearch/search/sort/FieldSortBuilder.java#L306-L321)

#### Analysis
~- [x] Return reloaded analyzers in _reload_search_ananlyzer response http://github.com/elastic/elasticsearch/pull/43813 (issue: http://github.com/elastic/elasticsearch/issues/43804)~ Experimental
~- [x] Allow reloading of search time analyzers http://github.com/elastic/elasticsearch/pull/43313 (issue: http://github.com/elastic/elasticsearch/issues/29051)~ Experimental
~- [x] Allow reloading of search time analyzers http://github.com/elastic/elasticsearch/pull/42888 (issue: http://github.com/elastic/elasticsearch/issues/29051)~ Experimental
~- [x] Allow reloading of search time analyzers http://github.com/elastic/elasticsearch/pull/42669 (issue: http://github.com/elastic/elasticsearch/issues/29051)~ Experimental

#### CCR
- [x] Replicate aliases in cross-cluster replication http://github.com/elastic/elasticsearch/pull/41815 (issue: http://github.com/elastic/elasticsearch/issues/41396)

#### Cluster Coordination
- [x] Add voting-only master node http://github.com/elastic/elasticsearch/pull/43410 (issue: http://github.com/elastic/elasticsearch/issues/14340)

#### Data Frame
~- [ ] Add a frequency option to transform config, default 1m http://github.com/elastic/elasticsearch/pull/44120~ N/A
~- [ ] Add node attr to GET _stats http://github.com/elastic/elasticsearch/pull/43842 (issue: http://github.com/elastic/elasticsearch/issues/43743)~ N/A
~- [ ] Add deduced mappings to _preview response payload http://github.com/elastic/elasticsearch/pull/43742 (issue: http://github.com/elastic/elasticsearch/issues/39250)~ N/A
~- [ ] Add support for allow_no_match for endpoints http://github.com/elastic/elasticsearch/pull/43490 (issue: http://github.com/elastic/elasticsearch/issues/42766)~ N/A
~- [ ] Add version and create_time to transform config http://github.com/elastic/elasticsearch/pull/43384 (issue: http://github.com/elastic/elasticsearch/issues/43037)~ N/A
~- [ ] Have sum map to a double to prevent overflows http://github.com/elastic/elasticsearch/pull/43213~ N/A
~- [ ] Add new pipeline field to dest config http://github.com/elastic/elasticsearch/pull/43124 (issue: http://github.com/elastic/elasticsearch/issues/43061)~ N/A
~- [ ] Add support for weighted_avg agg http://github.com/elastic/elasticsearch/pull/42646~ N/A

#### Distributed
- [x] Improve Close Index Response http://github.com/elastic/elasticsearch/pull/39687 (issue: http://github.com/elastic/elasticsearch/issues/33888)

#### Features/Indices APIs
~- [ ] Remove "template" field in IndexTemplateMetaData http://github.com/elastic/elasticsearch/pull/42099 (issue: http://github.com/elastic/elasticsearch/issues/38502)~ N/A

#### Features/Watcher
- [x] Watcher: Allow to execute actions for each element in array http://github.com/elastic/elasticsearch/pull/41997 (issue: http://github.com/elastic/elasticsearch/issues/34546)

#### Infra/Core
~- [ ] Deprecation info for joda-java migration on 7.x http://github.com/elastic/elasticsearch/pull/42659 (issue: http://github.com/elastic/elasticsearch/issues/42010)~ N/A

#### Machine Learning
~- [ ] Add version and create_time to data frame analytics config http://github.com/elastic/elasticsearch/pull/43683~ N/A
- [x] Report exponential_avg_bucket_processing_time which gives more weight to recent buckets http://github.com/elastic/elasticsearch/pull/43189 (issue: http://github.com/elastic/elasticsearch/issues/29857)
~- [ ] Adding support for geo_shape, geo_centroid, geo_point in datafeeds http://github.com/elastic/elasticsearch/pull/42969 (issue: http://github.com/elastic/elasticsearch/issues/42820)~ N/A
- [x] Report timing stats as part of the Job stats response http://github.com/elastic/elasticsearch/pull/42709 (issue: http://github.com/elastic/elasticsearch/issues/29857)
~- [ ] Add earliest and latest timestamps to field stats in find_file_structure response http://github.com/elastic/elasticsearch/pull/42890~  Find File Structure API not implemented

#### Mapping
~- [ ] Add dims parameter to dense_vector mapping http://github.com/elastic/elasticsearch/pull/43444~ Dense vecotr field mapping still experimental

#### Reindex
- [x] Reindex max_docs parameter name http://github.com/elastic/elasticsearch/pull/41894 (issue: http://github.com/elastic/elasticsearch/issues/24344)

#### Snapshot/Restore
~- [ ] Add SAS Token Authentication Support to Azure Repo Plugin http://github.com/elastic/elasticsearch/pull/42982 (issue: http://github.com/elastic/elasticsearch/issues/42117)~ No change needed, Config only
- [x] Add custom metadata to snapshots http://github.com/elastic/elasticsearch/pull/41281 (issue: http://github.com/elastic/elasticsearch/issues/40638)

#### Analysis
~- [ ] Issue deprecation warnings for preconfigured delimited_payload_filter http://github.com/elastic/elasticsearch/pull/43684 (issues: http://github.com/elastic/elasticsearch/issues/26625, http://github.com/elastic/elasticsearch/issues/43568)~

#### Infra/REST API
- [x] Remove deprecated _source_exclude and _source_include from get API spec http://github.com/elastic/elasticsearch/pull/42188

#### Recovery
- [x] Make Recovery API support `detailed` params http://github.com/elastic/elasticsearch/pull/29076 (issue: http://github.com/elastic/elasticsearch/issues/28910)

## Other

[ ] Look into removing test skips related to: https://github.com/elastic/elasticsearch/issues/44320#issuecomment-517584062

**Comment by russcam** [comment]
[7.3.0 is now released on Nuget](https://www.nuget.org/packages/NEST/7.3.0). Closing this
