### ISSUE TITLE
7.4 meta ticket

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#4133]
Ticket to track progress on 7.4 client release.

### Breaking changes

**Infra/REST API**

- [x] Update the schema for the REST API specification [#42346](https://github.com/elastic/elasticsearch/pull/42346) (issue: [#35262](https://github.com/elastic/elasticsearch/issues/35262))

**Search**

- [x] Use float instead of double for query vectors. [#46004](https://github.com/elastic/elasticsearch/pull/46004)

**Snapshot/Restore**

- [x] Provide an Option to Use Path-Style-Access with S3 Repo [#41966](https://github.com/elastic/elasticsearch/pull/41966) (issue: [#41816](https://github.com/elastic/elasticsearch/issues/41816))

**Transforms**

- [x] Improve response format of transform stats endpoint [#44350](https://github.com/elastic/elasticsearch/pull/44350) (issue: [#43767](https://github.com/elastic/elasticsearch/issues/43767))

### Breaking Java changes

**Geo**

- [x] Geo: Change order of parameter in Geometries to lon, lat [#45332](https://github.com/elastic/elasticsearch/pull/45332) (issue: [#45048](https://github.com/elastic/elasticsearch/issues/45048))

### Deprecations

**Infra/Core**

- [x] Add node.processors setting in favor of processors [#45855](https://github.com/elastic/elasticsearch/pull/45855)

**Machine Learning**

- [x] Deprecate the ability to update datafeed’s job_id. [#44691](https://github.com/elastic/elasticsearch/pull/44691) (issue: [#44615](https://github.com/elastic/elasticsearch/issues/44615))

### New features

**Aggregations**

- [x] Support Range Fields in Histogram and Date Histogram [#45395](https://github.com/elastic/elasticsearch/pull/45395)
- [x] Add Cumulative Cardinality agg (and Data Science plugin) [#43661](https://github.com/elastic/elasticsearch/pull/43661) (issue: [#43550](https://github.com/elastic/elasticsearch/issues/43550))

**Analysis**

- [x] Add support for inlined user dictionary in the Kuromoji plugin [#45489](https://github.com/elastic/elasticsearch/pull/45489) (issue: [#25343](https://github.com/elastic/elasticsearch/issues/25343))

**Authorization**

- [x] ~Add granular privileges for API keys [#42020](https://github.com/elastic/elasticsearch/pull/42020)~ no changes needed as PR was closed

**Features/ILM**

- [x] Add Snapshot Lifecycle Management [#43934](https://github.com/elastic/elasticsearch/pull/43934) (issue: [#38461](https://github.com/elastic/elasticsearch/issues/38461))

**Features/Watcher**

- [x] Add max_iterations configuration to watcher action with foreach execution [#45715](https://github.com/elastic/elasticsearch/pull/45715) (issues: [#41997](https://github.com/elastic/elasticsearch/issues/41997), [#45169](https://github.com/elastic/elasticsearch/issues/45169))

**Geo**

- [x] New `shape` field type for indexing Cartesian Geometries [#43644](https://github.com/elastic/elasticsearch/pull/43644) - via https://github.com/elastic/elasticsearch/pull/45363 - PR: https://github.com/elastic/elasticsearch-net/pull/4154
- [x] [SPATIAL] New ShapeQueryBuilder for querying indexed cartesian geometry [#45108](https://github.com/elastic/elasticsearch/pull/45108) (issue: [#44980](https://github.com/elastic/elasticsearch/issues/44980)) - PR: https://github.com/elastic/elasticsearch-net/pull/4155
- [x] ~[GEO] New ShapeFieldMapper for indexing cartesian geometries [#44980](https://github.com/elastic/elasticsearch/pull/44980)~ no client changes needed, accounted for in #4155 and #4154 
- [x] Add Circle Processor [#43851](https://github.com/elastic/elasticsearch/pull/43851) (issue: [#43554](https://github.com/elastic/elasticsearch/issues/43554)) - PR: https://github.com/elastic/elasticsearch-net/pull/4161

### Enhancements

**Aggregations**

- [x] Add more flexibility to MovingFunction window alignment [#44360](https://github.com/elastic/elasticsearch/pull/44360) (issue: [#42181](https://github.com/elastic/elasticsearch/issues/42181))
- [x] Allow pipeline aggs to select specific buckets from multi-bucket aggs [#44179](https://github.com/elastic/elasticsearch/pull/44179)

**Analysis**

- [x] Allow all token/char filters in normalizers [#43803](https://github.com/elastic/elasticsearch/pull/43803) (issue: [#43758](https://github.com/elastic/elasticsearch/issues/43758))

**CCR**

- [x] Include leases in error message when operations no longer available [#45681](https://github.com/elastic/elasticsearch/pull/45681)

**CRUD**

- [x] Return seq_no and primary_term for noop update [#44603](https://github.com/elastic/elasticsearch/pull/44603) (issue: [#42497](https://github.com/elastic/elasticsearch/issues/42497))

**Features/ILM**

- [x] Add node setting for disabling SLM [#46794](https://github.com/elastic/elasticsearch/pull/46794) (issue: [#38461](https://github.com/elastic/elasticsearch/issues/38461))
- [x] Include in-progress snapshot for a policy with get SLM policy API [#45245](https://github.com/elastic/elasticsearch/pull/45245)
- [x] Add option to filter ILM explain response [#44777](https://github.com/elastic/elasticsearch/pull/44777) (issue: [#44189](https://github.com/elastic/elasticsearch/issues/44189))
- [x] Expose index age in ILM explain output [#44457](https://github.com/elastic/elasticsearch/pull/44457) (issue: [#38988](https://github.com/elastic/elasticsearch/issues/38988))

**Features/Indices APIs**

- [x] Add Clone Index API [#44267](https://github.com/elastic/elasticsearch/pull/44267) (issue: [#44128](https://github.com/elastic/elasticsearch/issues/44128))
- [x] Add description to force-merge tasks [#41365](https://github.com/elastic/elasticsearch/pull/41365) (issue: [#15975](https://github.com/elastic/elasticsearch/issues/15975))

**Features/Watcher**

- [x] Watcher reporting: add email warning if CSV attachment contains values that may be interperted as formulas [#44460](https://github.com/elastic/elasticsearch/pull/44460)

**Machine Learning**

- [x] Introduce formal node ML role [#45174](https://github.com/elastic/elasticsearch/pull/45174) (issues: [#29943](https://github.com/elastic/elasticsearch/issues/29943), [#43175](https://github.com/elastic/elasticsearch/issues/43175))
- [x] ~Improve CSV header row detection in find_file_structure [#45099](https://github.com/elastic/elasticsearch/pull/45099) (issue: [#45047](https://github.com/elastic/elasticsearch/issues/45047))~ N/A as client doesn't implement find_file_structure
- [x] ~Outlier detection should only fetch docs that have the analyzed fields [#44944](https://github.com/elastic/elasticsearch/pull/44944)~ N/A to client
- [x] ~Persist DatafeedTimingStats with RefreshPolicy.NONE by default [#44940](https://github.com/elastic/elasticsearch/pull/44940) (issue: [#44792](https://github.com/elastic/elasticsearch/issues/44792))~ N/A to client
- [x] Add result_type field to TimingStats and DatafeedTimingStats documents [#44812](https://github.com/elastic/elasticsearch/pull/44812) - PR: https://github.com/elastic/elasticsearch-net/pull/4164
- [x] Implement exponential average search time per hour statistics. [#44683](https://github.com/elastic/elasticsearch/pull/44683) (issue: [#29857](https://github.com/elastic/elasticsearch/issues/29857))
- [x] ~Add r_squared eval metric to regression [#44248](https://github.com/elastic/elasticsearch/pull/44248)~ N/A: relates to dataframes APIs
- [x] ~Adds support for regression.mean_squared_error to eval API [#44140](https://github.com/elastic/elasticsearch/pull/44140)~ No client changes needed, dataframes are not implemented.
- [x] Add DatafeedTimingStats.average_search_time_per_bucket_ms and TimingStats.total_bucket_processing_time_ms stats [#44125](https://github.com/elastic/elasticsearch/pull/44125) (issue: [#29857](https://github.com/elastic/elasticsearch/issues/29857)) @russcam
- [x] ~Add DatafeedTimingStats to datafeed GetDatafeedStatsAction.Response [#43045](https://github.com/elastic/elasticsearch/pull/43045) (issue: [#29857](https://github.com/elastic/elasticsearch/issues/29857))~ Not implemented in client

**Ranking**

- [x] Search enhancement: pinned queries [#44345](https://github.com/elastic/elasticsearch/pull/44345) (issue: [#44074](https://github.com/elastic/elasticsearch/issues/44074))
- [x] Add l1norm and l2norm distances for vectors [#44116](https://github.com/elastic/elasticsearch/pull/44116) (issue: [#37947](https://github.com/elastic/elasticsearch/issues/37947))

**Search**

- [x] Adds usage stats for vectors: [#44512](https://github.com/elastic/elasticsearch/pull/44512) - PR: https://github.com/elastic/elasticsearch-net/pull/4151
- [x] ~Associate sub-requests to their parent task in multi search API [#44492](https://github.com/elastic/elasticsearch/pull/44492)~ no client changes needed
- [x] Cancel search task on connection close [#43332](https://github.com/elastic/elasticsearch/pull/43332)

**Snapshot/Restore**

- [x] add disable_chunked_encoding configuration [#44052](https://github.com/elastic/elasticsearch/pull/44052) - PR: https://github.com/elastic/elasticsearch-net/pull/4146
- [x] Repository Cleanup Endpoint [#43900](https://github.com/elastic/elasticsearch/pull/43900) - - PR: https://github.com/elastic/elasticsearch-net/pull/4145

### Bug fixes

**Analysis**

- [x] ~Fix AnalyzeAction response serialization [#44284](https://github.com/elastic/elasticsearch/pull/44284) (issue: [#44078](https://github.com/elastic/elasticsearch/issues/44078))~ Doesn't look like this change affects the client.

**CRUD**

- [x] ~Do not allow version in Rest Update API [#43516](https://github.com/elastic/elasticsearch/pull/43516) (issue: [#42497](https://github.com/elastic/elasticsearch/issues/42497))~ no client changes needed

**Features/ILM**

- [x] Updated slm API spec parameters and URL [#44797](https://github.com/elastic/elasticsearch/pull/44797)

**Infra/REST API**

- [x] ~Add is_write_index column to cat.aliases [#44772](https://github.com/elastic/elasticsearch/pull/44772)~ no client changes needed, code change was implemented in 6.4.

**Machine Learning**

- [x] ~Rename outlier detection method values `knn` and `tnn` to `distance_kth_nn` and `distance_knn` respectively to match the API. [#598](https://github.com/elastic/ml-cpp/pull/598)~ no changes needed, contained in Dataframes and this is not implemented in the client.

**Mapping**

- [x] ~Add include_type_name in indices.exitst REST API spec [#43910](https://github.com/elastic/elasticsearch/pull/43910) (issue: [#43905](https://github.com/elastic/elasticsearch/issues/43905))~ no changes needed, PR was closed and spec change not implemented in 7.4.

**Rollup**

- [x] ~Fix Rollup job creation to work with templates [#43943](https://github.com/elastic/elasticsearch/pull/43943)~ no changes needed.

**Snapshot/Restore**

- [x] ~Make Timestamps Returned by Snapshot APIs Consistent [#43148](https://github.com/elastic/elasticsearch/pull/43148) (issue: [#43074](https://github.com/elastic/elasticsearch/issues/43074))~ no changes needed.

**Transforms**

- [x] ~Respond with 409 status code when failing _stop [#44231](https://github.com/elastic/elasticsearch/pull/44231) (issue: [#44103](https://github.com/elastic/elasticsearch/issues/44103))~ no changes needed.
- [x] ~Audit message missing for autostop [#43984](https://github.com/elastic/elasticsearch/pull/43984) (issue: [#43977](https://github.com/elastic/elasticsearch/issues/43977))~ no changes needed.

**Comment by Mpdreamz** [comment]
Checked:

- [x] Improve response format of transform stats endpoint #44350 (issue: #43767) 

Since we do not support data frame just yet

**Comment by Mpdreamz** [comment]
- [x] Geo: Change order of parameter in Geometries to lon, lat #45332 (issue: #45048)

Does not affect us.

**Comment by Mpdreamz** [comment]
- [x] Add node.processors setting in favor of processors #45855 

Node settings will be passed to on `DynamicDictionary`

**Comment by Mpdreamz** [comment]
- [x]  Allow pipeline aggs to select specific buckets from multi-bucket aggs #44179

No impact on us

**Comment by Mpdreamz** [comment]
- [x] Allow all token/char filters in normalizers #43803 (issue: #43758)

We already pass everything through for the server to validate

**Comment by Mpdreamz** [comment]
- [x] Include leases in error message when operations no longer available #45681 

No impact on us

**Comment by Mpdreamz** [comment]
- [x] Return seq_no and primary_term for noop update #44603 (issue: #42497)

This actually fixes a bug for us, we assume these were always returned and are non nullable in our mapping

**Comment by Mpdreamz** [comment]
- [x]  Add node setting for disabling SLM #46794 (issue: #38461)

No impact on us.

**Comment by Mpdreamz** [comment]
TODO https://github.com/elastic/elasticsearch/pull/45245 also mentions `last_success` which we currently do not map for `GetSnapshotLifecycle`

**Comment by Mpdreamz** [comment]
- [x] Add description to force-merge tasks #41365 (issue: #15975)

`description` already comes through on get task responses

**Comment by Mpdreamz** [comment]
- [x] Watcher reporting: add email warning if CSV attachment contains values that may be interperted as formulas #44460

Does not affect us afaict.

**Comment by russcam** [comment]
> Support WKT point conversion to geo_point type #44107 (issue: #41821)

For this, I was thinking we can extend `GeoLocation` to support deserializing from this, similar to what we have done for GeoShapes i.e. deserialize from WKT (and serialize to WKT when has been deserialized from WKT).

**Comment by Mpdreamz** [comment]
- [x] Cancel search task on connection close #43332

Aborting or closing a request in the client will take care of this. 

An abort in .NET results in a tcp reset which does not put the connection in `TIME_WAIT` a dispose will result in a FIN which does result in a `TIME_WAIT`. 

Either way the connection will be closed and the search task will be aborted on the server

Validated on with WireShark on Linux netcoreapp2.2 which uses the `ManagedSocketsHandler`.

**Comment by Mpdreamz** [comment]
- [x] Add l1norm and l2norm distances for vectors #44116 (issue: #37947)

Painless changes only

**Comment by Mpdreamz** [comment]
>  Support Range Fields in Histogram and Date Histogram #45395

Change that now allows you to target range fields, awesome feature. No REST changes

**Comment by codebrain** [comment]
> TODO [elastic/elasticsearch#45245](https://github.com/elastic/elasticsearch/pull/45245) also mentions `last_success` which we currently do not map for `GetSnapshotLifecycle`

Implemented in https://github.com/elastic/elasticsearch-net/pull/4162

**Comment by russcam** [comment]
Closing this ticket as superseded by #4174
