### ISSUE TITLE
7.4.1 meta ticket

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#4174]
Ticket to track progress on 7.4.1 client release.

### Enhancements

**Authorization**

- [x] Add `manage_own_api_key` cluster privilege [#45897](https://github.com/elastic/elasticsearch/pull/45897) (issue: [#40031](https://github.com/elastic/elasticsearch/issues/40031)) - PR: https://github.com/elastic/elasticsearch-net/pull/4178
    *   ~(see above) Consider `owner` flag when retrieving/invalidating keys with API key service [#45421](https://github.com/elastic/elasticsearch/pull/45421) (issue: [#40031](https://github.com/elastic/elasticsearch/issues/40031))~ No client changes needed in lieu of above.
- [x] REST API changes for manage-own-api-key privilege [#44936](https://github.com/elastic/elasticsearch/pull/44936) (issue: [#40031](https://github.com/elastic/elasticsearch/issues/40031)) - PR: https://github.com/elastic/elasticsearch-net/pull/4178
- [x] ~Simplify API key service API [#44935](https://github.com/elastic/elasticsearch/pull/44935) (issue: [#40031](https://github.com/elastic/elasticsearch/issues/40031))~ No client changes needed.

**Geo**

- [x] Support WKT point conversion to geo_point type [#44107](https://github.com/elastic/elasticsearch/pull/44107) (issue: [#41821](https://github.com/elastic/elasticsearch/issues/41821)) - implemented in https://github.com/elastic/elasticsearch-net/pull/4222

### Bug fixes

**Geo**

- [ ] Geo: add validator that only checks altitude [#43893](https://github.com/elastic/elasticsearch/pull/43893) - .NET client might need to remove range checks?

### HTTP changes

- [x] ~Starting in version 7.4, a `+` in a URL will be encoded as `%2B` by all REST API functionality. Prior versions handled a `+` as a single space. If your application requires handling `+` as a single space you can return to the old behaviour by setting the system property `es.rest.url_plus_as_space` to `true`. Note that this behaviour is deprecated and setting this system property to `true` will cease to be supported in version 8.~ The client already encodes `+` as `%2B` using `Uri.EscapeDataString(str)`

### Enhancements

**Engine**

- [x] ~Avoid unneeded refresh with concurrent realtime gets [#47895](https://github.com/elastic/elasticsearch/pull/47895)~ - no client changes needed
- [x] ~Sync before trimUnreferencedReaders to improve index preformance [#47790](https://github.com/elastic/elasticsearch/pull/47790) (issues: [#46201](https://github.com/elastic/elasticsearch/issues/46201), [#46203](https://github.com/elastic/elasticsearch/issues/46203))~ - no client changes needed
- [x] ~Limit number of retaining translog files for peer recovery [#47414](https://github.com/elastic/elasticsearch/pull/47414)~ - no client changes needed

**Infra/Circuit Breakers**

- [x] ~Emit log message when parent circuit breaker trips [#47000](https://github.com/elastic/elasticsearch/pull/47000)~ - no client changes needed

**Machine Learning**

- [x] ~[ML] Throttle the delete-by-query of expired results [#47177](https://github.com/elastic/elasticsearch/pull/47177) (issues: [#47003](https://github.com/elastic/elasticsearch/issues/47003), [#47103](https://github.com/elastic/elasticsearch/issues/47103))~ - no client changes needed

### Bug fixes

**Aggregations**

- [x] ~DocValueFormat implementation for date range fields [#47472](https://github.com/elastic/elasticsearch/pull/47472) (issues: [#47323](https://github.com/elastic/elasticsearch/issues/47323), [#47469](https://github.com/elastic/elasticsearch/issues/47469))~ no client changes needed, client already supports `Format` property.

**Allocation**

- [x] ~Dangling indices strip aliases [#47581](https://github.com/elastic/elasticsearch/pull/47581)~ no client changes needed

**Analysis**

- [x] ~Reset Token position on reuse in predicate_token_filter [#47424](https://github.com/elastic/elasticsearch/pull/47424) (issue: [#47197](https://github.com/elastic/elasticsearch/issues/47197))~ no client changes needed

**Authentication**

- [x] ~Fix AD realm additional metadata [#47179](https://github.com/elastic/elasticsearch/pull/47179) (issue: [#45848](https://github.com/elastic/elasticsearch/issues/45848))~ no client changes needed

**Authorization**

- [x] ~Use _should_ clause instead of _filter_ when querying native privileges [#47019](https://github.com/elastic/elasticsearch/pull/47019)~ - no client changes needed

**CCR**

- [x] ~Do not auto-follow closed indices [#47721](https://github.com/elastic/elasticsearch/pull/47721) (issue: [#47582](https://github.com/elastic/elasticsearch/issues/47582))~ - no client changes needed
- [x] ~Relax maxSeqNoOfUpdates assertion in FollowingEngine [#47188](https://github.com/elastic/elasticsearch/pull/47188) (issue: [#47137](https://github.com/elastic/elasticsearch/issues/47137))~ no client changes needed

**Cluster Coordination**

- [x] ~Omit writing index metadata for non-replicated closed indices on data-only node [#47285](https://github.com/elastic/elasticsearch/pull/47285) (issue: [#47276](https://github.com/elastic/elasticsearch/issues/47276))~ - no client changes needed

**Features/ILM+SLM**

- [x] ~Throw error retrieving non-existent SLM policy [#47679](https://github.com/elastic/elasticsearch/pull/47679) (issue: [#47664](https://github.com/elastic/elasticsearch/issues/47664))~ no client changes needed

**Features/Indices APIs**

- [x] ~Fix Rollover error when alias has closed indices [#47148](https://github.com/elastic/elasticsearch/pull/47148) (issue: [#47146](https://github.com/elastic/elasticsearch/issues/47146))~ no client changes needed

**Features/Java High Level REST Client**

- [x] ~Fix ILM HLRC Javadoc→Documentation links [#48083](https://github.com/elastic/elasticsearch/pull/48083)~ no client changes needed

**Features/Monitoring**

- [x] ~[Monitoring] Add new cluster privilege now necessary for the stack monitoring ui [#47871](https://github.com/elastic/elasticsearch/pull/47871)~ no client changes needed

**Infra/Scripting**

- [x] ~Drop stored scripts with the old style-id [#48078](https://github.com/elastic/elasticsearch/pull/48078) (issue: [#47593](https://github.com/elastic/elasticsearch/issues/47593))~ - no client changes needed

**Machine Learning**

- [x] ~[ML] Fix detection of syslog-like timestamp in find_file_structure [#47970](https://github.com/elastic/elasticsearch/pull/47970)~ - no client changes needed
- [x] ~[ML] Reinstate ML daily maintenance actions [#47103](https://github.com/elastic/elasticsearch/pull/47103) (issue: [#47003](https://github.com/elastic/elasticsearch/issues/47003))~ - no client changes needed

**Network**

- [x] ~Fix es.http.cname_in_publish_address Deprecation Logging [#47451](https://github.com/elastic/elasticsearch/pull/47451) (issue: [#47436](https://github.com/elastic/elasticsearch/issues/47436))~ - no client changes needed

**SQL**

- [x]  ~SQL: Fix issue with negative literels and parentheses [#48113](https://github.com/elastic/elasticsearch/pull/48113) (issue: [#48009](https://github.com/elastic/elasticsearch/issues/48009))~ - no client changes needed
- [x] ~SQL: add "format" for "full" date range queries [#48073](https://github.com/elastic/elasticsearch/pull/48073) (issue: [#48033](https://github.com/elastic/elasticsearch/issues/48033))~ - no client changes needed
- [x] ~SQL: Allow whitespaces in escape patterns [#47577](https://github.com/elastic/elasticsearch/pull/47577) (issue: [#47401](https://github.com/elastic/elasticsearch/issues/47401))~ - no client changes needed
- [x] ~SQL: fix multi full-text functions usage with aggregate functions [#47444](https://github.com/elastic/elasticsearch/pull/47444) (issue: [#47365](https://github.com/elastic/elasticsearch/issues/47365))~ - no client changes needed
- [x] ~SQL: wrong number of values for columns [#42122](https://github.com/elastic/elasticsearch/pull/42122)~ - no client changes needed

**Search**

- [x] ~Fix alias field resolution in match query [#47369](https://github.com/elastic/elasticsearch/pull/47369)~ - no client changes needed

**Snapshot/Restore**

- [x] ~Fix Bug in Azure Repo Exception Handling [#47968](https://github.com/elastic/elasticsearch/pull/47968)~ - no client changes needed
- [x] ~Fix Snapshot Corruption in Edge Case [#47552](https://github.com/elastic/elasticsearch/pull/47552) (issues: [#46250](https://github.com/elastic/elasticsearch/issues/46250), [#47550](https://github.com/elastic/elasticsearch/issues/47550))~ - no client changes needed

**Store**

- [x] ~Allow truncation of clean translog [#47866](https://github.com/elastic/elasticsearch/pull/47866)~ - no client changes needed

**Transform**

- [x] ~[7.5][Transform] prevent assignment if any node is older than 7.4 [#48055](https://github.com/elastic/elasticsearch/pull/48055) (issue: [#48019](https://github.com/elastic/elasticsearch/issues/48019))~ - no client changes needed
- [x] ~[Transform] prevent assignment to nodes older than 7.4 [#48044](https://github.com/elastic/elasticsearch/pull/48044) (issue: [#48019](https://github.com/elastic/elasticsearch/issues/48019))~ - no client changes needed
- [x] ~[ML][Transforms] fix bwc serialization with 7.3 [#48021](https://github.com/elastic/elasticsearch/pull/48021)~ - no client changes needed

**Comment by russcam** [comment]
Closing this as 7.4.1 is now released
