### ISSUE TITLE
[meta] 7.5 release

### ISSUE THREAD

**Issue by Mpdreamz** [elastic/elasticsearch-net#4232]
### Features/ILM+SLM
- [x] Add API to execute SLM retention on-demand elastic/elasticsearch#47405 (issues: elastic/elasticsearch#43663, elastic/elasticsearch#46508) - PR: https://github.com/elastic/elasticsearch-net/pull/4258
- [x] Add retention to Snapshot Lifecycle Management elastic/elasticsearch#46407 (issues: elastic/elasticsearch#38461, elastic/elasticsearch#43663, elastic/elasticsearch#45362) - PR: https://github.com/elastic/elasticsearch-net/pull/4261

### Features/Ingest
- [x] Add enrich processor elastic/elasticsearch#48039 (issue: elastic/elasticsearch#32789) - PR: https://github.com/elastic/elasticsearch-net/pull/4275

### Machine Learning
- [x] ~Implement evaluation API for multiclass classification problem elastic/elasticsearch#47126 (issue: elastic/elasticsearch#46735)~ no client changes needed as API is not GA
- [x] ~Implement new analysis type: classification elastic/elasticsearch#46537 (issue: elastic/elasticsearch#46735)~ no client changes needed as API is not GA
 
### Aggregations
- [x] Support geotile_grid aggregation in composite agg sources elastic/elasticsearch#45810 (issue: elastic/elasticsearch#40568) - PR: https://github.com/elastic/elasticsearch-net/pull/4271
### Authorization
- [x] Add support to retrieve all API keys if user has privilege elastic/elasticsearch#47274 (issue: elastic/elasticsearch#46887) - PR: https://github.com/elastic/elasticsearch-net/pull/4272

### CCR
- [x] Add Pause/Resume Auto Follower APIs elastic/elasticsearch#47510 (issue: elastic/elasticsearch#46665) - PR: https://github.com/elastic/elasticsearch-net/pull/4273

### CRUD
- [x] ~Allow optype CREATE for append-only indexing operations elastic/elasticsearch#47169~ No client changes needed

### Features/ILM+SLM
- [x] Separate SLM stop/start/status API from ILM elastic/elasticsearch#47710 (issue: elastic/elasticsearch#43663) - PR: https://github.com/elastic/elasticsearch-net/pull/4245
- [x] Add support for POST requests to SLM Execute API elastic/elasticsearch#47061 - PR: https://github.com/elastic/elasticsearch-net/pull/4246

### Features/Ingest
- [x] Add the ability to require an ingest pipeline (also add default if not exist alread) elastic/elasticsearch#46847 - PR: https://github.com/elastic/elasticsearch-net/pull/4274
 
### Machine Learning
- [x] Add option to stop datafeed that finds no data elastic/elasticsearch#47922 - PR: https://github.com/elastic/elasticsearch-net/pull/4286
- [x] Add lazy assignment job config option elastic/elasticsearch#47726 - PR: https://github.com/elastic/elasticsearch-net/pull/4277
- [x] ~Additional outlier detection parameters elastic/elasticsearch#47600~ no client changes needed, API is not GA

### Transform
- ~[x] Add support for wait_for_checkpoint flag on _stop API elastic/elasticsearch#45469 (issue: elastic/elasticsearch#45293)~ still beta

### Aggregations
- [x] ~DocValueFormat implementation for date range fields elastic/elasticsearch#47472 (issues: elastic/elasticsearch#47323, elastic/elasticsearch#47469)~ no client changes needed

### CRUD
- [x] ~Use optype CREATE for single auto-id index requests elastic/elasticsearch#47353~ no client changes needed
- [x] ~Ignore replication for noop updates elastic/elasticsearch#46458 (issues: elastic/elasticsearch#41065, elastic/elasticsearch#44603, elastic/elasticsearch#46366)~ No client changes needed
 

### Features/ILM+SLM
- [x] Add SLM support to xpack usage and info APIs elastic/elasticsearch#48096 (issue: elastic/elasticsearch#43663) - PR: https://github.com/elastic/elasticsearch-net/pull/4264
- [x] Change policy_id to list type in slm.get_lifecycle elastic/elasticsearch#47766 (issue: elastic/elasticsearch#47765) - *no client changes needed as generator now emits `Ids` instead of `Id`. Will need to call out in breaking changes.
- [x] Throw error retrieving non-existent SLM policy elastic/elasticsearch#47679 (issue: elastic/elasticsearch#47664) - PR: https://github.com/elastic/elasticsearch-net/pull/4265
- [x] Fixes for API specification elastic/elasticsearch#46522 - *no client changes needed as introduced in 7.4.0*

### Features/Ingest
- [x] ~Allow dropping documents with auto-generated ID elastic/elasticsearch#46773 (issue: elastic/elasticsearch#46678)~ no client changes needed
- [x] ~Expose cache setting in UserAgentPlugin elastic/elasticsearch#46533~ no client changes needed

**Comment by Mpdreamz** [comment]
Integration branch `7.5 `is cut and brought up to date with the `rest-api-spec`

https://github.com/elastic/elasticsearch-net/compare/7.x...7.5?expand=1
