### ISSUE TITLE
7.7.0 meta ticket

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#4525]
## New APIs

The following APIs are marked as `stable` in 7.7 and require implementation.

 - ~[ ] async_search.delete.json~ - bumped to `7.7.1`
 - ~[ ] async_search.get.json~ - bumped to `7.7.1`
 - ~[ ] async_search.submit.json~ - bumped to `7.7.1`
 - [x] cat.ml_data_frame_analytics.json - https://github.com/elastic/elasticsearch-net/pull/4565
 - [x] cat.ml_datafeeds.json - https://github.com/elastic/elasticsearch-net/pull/4564
 - [x] cat.ml_jobs.json - https://github.com/elastic/elasticsearch-net/pull/4563
 - [x] cat.ml_trained_models.json - https://github.com/elastic/elasticsearch-net/pull/4562
 - [x] cat.transform.json - See: https://github.com/elastic/elasticsearch-net/pull/4557
 - [x] cluster.delete_component_template.json - marked as experimental
 - [x] cluster.get_component_template.json  - marked as experimental
 - [x] cluster.put_component_template.json  - marked as experimental
 - [x] indices.reload_search_analyzers.json - See: elastic/elasticsearch-net/pull/4529
 - [x] ml.estimate_model_memory.json - See: elastic/elasticsearch-net/pull/4530
 - [x] ml.set_upgrade_mode.json - See: elastic/elasticsearch-net/pull/4535
 - [x] security.get_builtin_privileges.json - See: elastic/elasticsearch-net/pull/4536
 - ~[ ] transform.delete_transform.json~ - bumped to `7.7.1`
 - ~[ ] transform.get_transform.json~ - bumped to `7.7.1`
 - ~[ ] transform.get_transform_stats.json~ - bumped to `7.7.1`
 - ~[ ] transform.preview_transform.json~ - bumped to `7.7.1`
 - ~[ ] transform.put_transform.json~ - bumped to `7.7.1`
 - ~[ ] transform.start_transform.json~ - bumped to `7.7.1`
 - ~[ ] transform.stop_transform.json~ - bumped to `7.7.1`
 - ~[ ] transform.update_transform.json~ - bumped to `7.7.1`

## API patches

- [x] https://github.com/elastic/elasticsearch/commit/03caeaad79bd29bda66f3af70791b06fc67a5e4f
- [x] https://github.com/elastic/elasticsearch/pull/54551

## Elasticsearch Release Notes

The following release notes were extracted 2020 04 01.

### Deprecations

Features/Features

 - [x] Add cluster.remote.connect to deprecation info API elastic/elasticsearch/pull/54142 [#54142] (issue: elastic/elasticsearch/issues/53924 [#53924])

Machine Learning

 - [x] [ML] renaming inference processor field field_mappings to new name field_map elastic/elasticsearch/pull/53433 [#53433]

Search

 - [x] Deprecate BoolQueryBuilder's mustNot field elastic/elasticsearch/pull/53125 [#53125]

### New features

Aggregations

 - [x] Add Boxplot Aggregation elastic/elasticsearch/pull/51948 [#51948] (issue: elastic/elasticsearch/issues/33112 [#33112])

Analysis

 - [x] add nori_number token filter in analysis-nori elastic/elasticsearch/pull/53583 [#53583] - https://github.com/elastic/elasticsearch-net/pull/4591

Geo

 - [x] Add support for distance queries on shape queries elastic/elasticsearch/pull/53468 [#53468]

 - [x] Add support for distance queries on geo_shape queries elastic/elasticsearch/pull/53466 [#53466] (issues: elastic/elasticsearch/issues/13351 [#13351], elastic/elasticsearch/issues/39237 [#39237])

 - [x] Add support for multipoint shape queries elastic/elasticsearch/pull/52564 [#52564] (issue: elastic/elasticsearch/issues/52133 [#52133])

 - [x] Add support for multipoint geoshape queries elastic/elasticsearch/pull/52133 [#52133] (issue: elastic/elasticsearch/issues/37318 [#37318])

Infra/Core

 - [x] Implement hidden indices elastic/elasticsearch/pull/50452 [#50452] (issues: elastic/elasticsearch/issues/50251 [#50251], elastic/elasticsearch/issues/50665 [#50665], elastic/elasticsearch/issues/50762 [#50762])

Mapping

 - [x] Introduce a `constant_keyword` field. elastic/elasticsearch/pull/49713 [#49713]

### Upgrades

Features/Ingest

 - [x] Support array for all string ingest processors elastic/elasticsearch/pull/53343 [#53343] (issue: elastic/elasticsearch/issues/51087 [#51087])

### Enhancements

Aggregations

 - [x] Add histogram field type support to boxplot aggs http://github.com/elastic/elasticsearch/pull/52265 [#52265] (issues: http://github.com/elastic/elasticsearch/issues/33112 [#33112], http://github.com/elastic/elasticsearch/issues/52233 [#52233])

 - [x] Implement top_metrics agg http://github.com/elastic/elasticsearch/pull/51155 [#51155] (issue: http://github.com/elastic/elasticsearch/issues/48069 [#48069]) - https://github.com/elastic/elasticsearch-net/pull/4594

Features/CAT APIs

 - [x] /_cat/shards support path stats http://github.com/elastic/elasticsearch/pull/53461 [#53461]

 - [x] Allow _cat indices & aliases to use indices options http://github.com/elastic/elasticsearch/pull/53248 [#53248] (issue: http://github.com/elastic/elasticsearch/issues/52304 [#52304])

Features/Ingest

 - [x] Add empty_value parameter to CSV processor http://github.com/elastic/elasticsearch/pull/51567 [#51567] - https://github.com/elastic/elasticsearch-net/pull/4597

Features/Stats

 - [x] ~Add analysis components and mapping types to the usage API. http://github.com/elastic/elasticsearch/pull/51031 [#51031]~ - not present in 7.7.0 https://github.com/elastic/elasticsearch/pull/51031#issuecomment-614447840

Infra/Core

 - [x] Implement hidden aliases http://github.com/elastic/elasticsearch/pull/52547 [#52547] (issue: http://github.com/elastic/elasticsearch/issues/52304 [#52304])

Ilm

 - [x] Allow forcemerge in the hot phase for ILM policies http://github.com/elastic/elasticsearch/pull/52073 [#52073] (issue: http://github.com/elastic/elasticsearch/issues/43165 [#43165]) - requires update to XML docs in client - https://github.com/elastic/elasticsearch-net/pull/4598

Machine Learning

 - [x] [ML] Add indices_options to datafeed config and update http://github.com/elastic/elasticsearch/pull/52793 [#52793] (issue: http://github.com/elastic/elasticsearch/issues/48056 [#48056])

Mapping

 - [x] Wildcard field - add normalizer support http://github.com/elastic/elasticsearch/pull/53851 [#53851]

 - [x] Wildcard field - added case insensitive search option http://github.com/elastic/elasticsearch/pull/53814 [#53814]

Reindex

 - [x] Reindex: allow comma separated source indices http://github.com/elastic/elasticsearch/pull/52044 [#52044] (issue: http://github.com/elastic/elasticsearch/issues/51949 [#51949])

**Comment by russcam** [comment]
Closing this as 7.7.0 is released
