### ISSUE TITLE
7.7.0 meta ticket (Part 3)

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#4534]
# 7.7.0 meta ticket

The following tickets tracks known (and potential) changes to the high level REST client.

Part 1: #4525 
Part 2: #4533 
Part 3: #4534 

## Elasticsearch Release Notes

The following release notes were extracted 2020 04 01.

This list needs to be reviewed for potential changes to the high level REST client. Note, it will contain references to new APIs as tracked in #4525 .

### Enhancements

Transform

 - [x] Transition Transforms to using hidden indices for notifcations index http://github.com/elastic/elasticsearch/pull/53773 [#53773] (issue: http://github.com/elastic/elasticsearch/issues/53762 [#53762])

 - [x] Create GET _cat/transforms API Issue http://github.com/elastic/elasticsearch/pull/53643 [#53643] (issue: http://github.com/elastic/elasticsearch/issues/51412 [#51412])

 - [x] [Transform] add support for script in group_by http://github.com/elastic/elasticsearch/pull/53167 [#53167] (issue: http://github.com/elastic/elasticsearch/issues/43152 [#43152])

 - [x] [Transform] implement node.transform to control where to run a transform http://github.com/elastic/elasticsearch/pull/52712 [#52712] (issues: http://github.com/elastic/elasticsearch/issues/48734 [#48734], http://github.com/elastic/elasticsearch/issues/50033 [#50033], http://github.com/elastic/elasticsearch/issues/52200 [#52200])

 - [x] [Transform] add support for filter aggregation http://github.com/elastic/elasticsearch/pull/52483 [#52483] (issue: http://github.com/elastic/elasticsearch/issues/52151 [#52151])

 - [x] [Transform] provide exponential_avg stats for batch transforms http://github.com/elastic/elasticsearch/pull/52041 [#52041] (issue: http://github.com/elastic/elasticsearch/issues/52037 [#52037])

 - [x] [Transform] improve irrecoverable error detection - part 2 http://github.com/elastic/elasticsearch/pull/52003 [#52003] (issue: http://github.com/elastic/elasticsearch/issues/51820 [#51820])

 - [x] [Transform] mark transform API's stable http://github.com/elastic/elasticsearch/pull/51862 [#51862]

 - [x] [Transform] improve irrecoverable error detection http://github.com/elastic/elasticsearch/pull/51820 [#51820] (issue: http://github.com/elastic/elasticsearch/issues/50135 [#50135])

 - [x] [Transform] add support for percentile aggs http://github.com/elastic/elasticsearch/pull/51808 [#51808] (issue: http://github.com/elastic/elasticsearch/issues/51663 [#51663])

 - [x] [Transform] disallow fieldnames with a dot at start and/or end http://github.com/elastic/elasticsearch/pull/51369 [#51369]

 - [x] [Transform] avoid mapping problems with index templates http://github.com/elastic/elasticsearch/pull/51368 [#51368] (issue: http://github.com/elastic/elasticsearch/issues/51321 [#51321])

 - [x] [Transform] Handle permanent bulk indexing errors http://github.com/elastic/elasticsearch/pull/51307 [#51307] (issue: http://github.com/elastic/elasticsearch/issues/50122 [#50122])

 - [x] [Transform] Improve force stop robustness in case of an error http://github.com/elastic/elasticsearch/pull/51072 [#51072]

Aggregations

 - [x] Fix date_nanos in composite aggs http://github.com/elastic/elasticsearch/pull/53315 [#53315] (issue: http://github.com/elastic/elasticsearch/issues/53168 [#53168])

 - [x] Fix composite agg sort bug http://github.com/elastic/elasticsearch/pull/53296 [#53296] (issue: http://github.com/elastic/elasticsearch/issues/52480 [#52480])

 - [x] Decode max and min optimization more carefully http://github.com/elastic/elasticsearch/pull/52336 [#52336] (issue: http://github.com/elastic/elasticsearch/issues/52220 [#52220])

 - [x] Fix a DST error in date_histogram http://github.com/elastic/elasticsearch/pull/52016 [#52016] (issue: http://github.com/elastic/elasticsearch/issues/50265 [#50265])

 - [x] Use #name() instead of #simpleName() when generating doc values http://github.com/elastic/elasticsearch/pull/51920 [#51920] (issues: http://github.com/elastic/elasticsearch/issues/50307 [#50307], http://github.com/elastic/elasticsearch/issues/51847 [#51847])

 - [x] Fix a sneaky bug in rare_terms http://github.com/elastic/elasticsearch/pull/51868 [#51868] (issue: http://github.com/elastic/elasticsearch/issues/51020 [#51020])

 - [x] Support time_zone on composite's date_histogram http://github.com/elastic/elasticsearch/pull/51172 [#51172] (issues: http://github.com/elastic/elasticsearch/issues/45199 [#45199], http://github.com/elastic/elasticsearch/issues/45200 [#45200])

Allocation

 - [x] Improve performance of shards limits decider http://github.com/elastic/elasticsearch/pull/53577 [#53577] (issue: http://github.com/elastic/elasticsearch/issues/53559 [#53559])

Analysis

 - [x] Mask wildcard query special characters on keyword queries http://github.com/elastic/elasticsearch/pull/53127 [#53127] (issue: http://github.com/elastic/elasticsearch/issues/46300 [#46300])

 - [x] Fix caching for PreConfiguredTokenFilter http://github.com/elastic/elasticsearch/pull/50912 [#50912] (issue: http://github.com/elastic/elasticsearch/issues/50734 [#50734])

Audit

 - [x] Logfile audit settings validation http://github.com/elastic/elasticsearch/pull/52537 [#52537] (issues: http://github.com/elastic/elasticsearch/issues/47038 [#47038], http://github.com/elastic/elasticsearch/issues/47711 [#47711], http://github.com/elastic/elasticsearch/issues/52357 [#52357])

Authentication

 - [x] Fix responses for the token APIs [OPEN] http://github.com/elastic/elasticsearch/pull/54532 [#54532] (issue: http://github.com/elastic/elasticsearch/issues/53323 [#53323])

 - [x] Fix potential bug in concurrent token refresh support http://github.com/elastic/elasticsearch/pull/53668 [#53668]

 - [x] Respect runas realm for ApiKey security operations http://github.com/elastic/elasticsearch/pull/52178 [#52178] (issue: http://github.com/elastic/elasticsearch/issues/51975 [#51975])

 - [x] Preserve ApiKey credentials for async verification http://github.com/elastic/elasticsearch/pull/51244 [#51244]

 - [x] Don't fallback to anonymous for tokens/apikeys http://github.com/elastic/elasticsearch/pull/51042 [#51042] (issue: http://github.com/elastic/elasticsearch/issues/50171 [#50171])

 - [x] Fail gracefully on invalid token strings http://github.com/elastic/elasticsearch/pull/51014 [#51014]

Authorization

 - [x] Explicitly require that delegate API keys have no privileges http://github.com/elastic/elasticsearch/pull/53647 [#53647]

 - [x] Allow _rollup_search with read privilege http://github.com/elastic/elasticsearch/pull/52043 [#52043] (issue: http://github.com/elastic/elasticsearch/issues/50245 [#50245])

CCR

 - [x] Put CCR tasks on (data && remote cluster clients) http://github.com/elastic/elasticsearch/pull/54146 [#54146] (issue: http://github.com/elastic/elasticsearch/issues/53924 [#53924])

 - [x] Handle no such remote cluster exception in ccr http://github.com/elastic/elasticsearch/pull/53415 [#53415] (issue: http://github.com/elastic/elasticsearch/issues/53225 [#53225])

 - [x] Fix shard follow task cleaner under security http://github.com/elastic/elasticsearch/pull/52347 [#52347] (issues: http://github.com/elastic/elasticsearch/issues/44702 [#44702], http://github.com/elastic/elasticsearch/issues/51971 [#51971])

CRUD

 - [x] Force execution of finish shard bulk request http://github.com/elastic/elasticsearch/pull/51957 [#51957] (issue: http://github.com/elastic/elasticsearch/issues/51904 [#51904])

 - [x] Return 429 status code when there's a read_only cluster block http://github.com/elastic/elasticsearch/pull/50166 [#50166] (issue: http://github.com/elastic/elasticsearch/issues/49393 [#49393])

Cluster Coordination

 - [x] Use special XContent registry for node tool http://github.com/elastic/elasticsearch/pull/54050 [#54050] (issue: http://github.com/elastic/elasticsearch/issues/53549 [#53549])

 - [x] Allow static cluster.max_voting_config_exclusions http://github.com/elastic/elasticsearch/pull/53717 [#53717] (issue: http://github.com/elastic/elasticsearch/issues/53455 [#53455])

 - [x] Allow joining node to trigger term bump http://github.com/elastic/elasticsearch/pull/53338 [#53338] (issue: http://github.com/elastic/elasticsearch/issues/53271 [#53271])

 - [x] Ignore timeouts with single-node discovery http://github.com/elastic/elasticsearch/pull/52159 [#52159]

Distributed

 - [x] Execute retention lease syncs under system context http://github.com/elastic/elasticsearch/pull/53838 [#53838] (issues: http://github.com/elastic/elasticsearch/issues/48430 [#48430], http://github.com/elastic/elasticsearch/issues/53751 [#53751])

 - [x] Exclude nested documents in LuceneChangesSnapshot http://github.com/elastic/elasticsearch/pull/51279 [#51279]

Engine

 - [x] Fix doc_stats and segment_stats of ReadOnlyEngine http://github.com/elastic/elasticsearch/pull/53345 [#53345] (issues: http://github.com/elastic/elasticsearch/issues/51303 [#51303], http://github.com/elastic/elasticsearch/issues/51331 [#51331])

 - [x] Do not wrap soft-deletes reader for segment stats http://github.com/elastic/elasticsearch/pull/51331 [#51331] (issues: http://github.com/elastic/elasticsearch/issues/51192 [#51192], http://github.com/elastic/elasticsearch/issues/51303 [#51303])

 - [x] Account soft-deletes in FrozenEngine http://github.com/elastic/elasticsearch/pull/51192 [#51192] (issue: http://github.com/elastic/elasticsearch/issues/50775 [#50775])

Features/CAT APIs

 - [x] Fix NPE in RestPluginsAction http://github.com/elastic/elasticsearch/pull/52620 [#52620] (issue: http://github.com/elastic/elasticsearch/issues/45321 [#45321])

Features/ILM+SLM

 - [x] Fix null config in SnapshotLifecyclePolicy.toRequest http://github.com/elastic/elasticsearch/pull/53328 [#53328] (issues: http://github.com/elastic/elasticsearch/issues/44465 [#44465], http://github.com/elastic/elasticsearch/issues/53171 [#53171])

 - [x] ILM Freeze step retry when not acknowledged http://github.com/elastic/elasticsearch/pull/53287 [#53287]

 - [x] ILM make the set-single-node-allocation retryable http://github.com/elastic/elasticsearch/pull/52077 [#52077] (issue: http://github.com/elastic/elasticsearch/issues/43401 [#43401])

 - [x] ILM fix the init step to actually be retryable http://github.com/elastic/elasticsearch/pull/52076 [#52076]

Features/Ingest

 - [x] Fix ingest pipeline _simulate api with empty docs never returns a res… http://github.com/elastic/elasticsearch/pull/52937 [#52937] (issue: http://github.com/elastic/elasticsearch/issues/52833 [#52833])

 - [x] Handle errors when evaluating if conditions in processors http://github.com/elastic/elasticsearch/pull/52543 [#52543] (issue: http://github.com/elastic/elasticsearch/issues/52339 [#52339])

 - [x] Fix delete enrich policy bug http://github.com/elastic/elasticsearch/pull/52179 [#52179] (issue: http://github.com/elastic/elasticsearch/issues/51228 [#51228])

 - [x] Fix ignore_missing in CsvProcessor http://github.com/elastic/elasticsearch/pull/51600 [#51600]

 - [x] Missing suffix for German Month "Juli" in Grok Pattern MONTH (#51579) http://github.com/elastic/elasticsearch/pull/51591 [#51591] (issue: http://github.com/elastic/elasticsearch/issues/51579 [#51579])

 - [x] Don't overwrite target field with SetSecurityUserProcessor http://github.com/elastic/elasticsearch/pull/51454 [#51454] (issue: http://github.com/elastic/elasticsearch/issues/51428 [#51428])

Features/Java High Level REST Client

 - [x] Add unsupported parameters to HLRC search request http://github.com/elastic/elasticsearch/pull/53745 [#53745]

 - [x] Fix AbstractBulkByScrollRequest slices parameter via Rest http://github.com/elastic/elasticsearch/pull/53068 [#53068] (issue: http://github.com/elastic/elasticsearch/issues/53044 [#53044])

 - [x] send the fields param via body instead of URL params (elastic#42232) http://github.com/elastic/elasticsearch/pull/48840 [#48840] (issues: http://github.com/elastic/elasticsearch/issues/42232 [#42232], http://github.com/elastic/elasticsearch/issues/42877 [#42877])

Features/Java Low Level REST Client

 - [x] Fix roles parsing in client nodes sniffer http://github.com/elastic/elasticsearch/pull/52888 [#52888] (issue: http://github.com/elastic/elasticsearch/issues/52864 [#52864])

Features/Monitoring

 - [x] Fix NPE in cluster state collector for monitoring http://github.com/elastic/elasticsearch/pull/52371 [#52371] (issue: http://github.com/elastic/elasticsearch/issues/52317 [#52317])

Features/Stats

 - [x] Switch to AtomicLong for "IngestCurrent" metric to prevent negative values http://github.com/elastic/elasticsearch/pull/52581 [#52581] (issues: http://github.com/elastic/elasticsearch/issues/52406 [#52406], http://github.com/elastic/elasticsearch/issues/52411 [#52411])

Features/Watcher

 - [x] Disable Watcher script optimization for stored scripts http://github.com/elastic/elasticsearch/pull/53497 [#53497] (issue: http://github.com/elastic/elasticsearch/issues/40212 [#40212])

 - [x] The watcher indexing listener didn't handle document level exceptions. http://github.com/elastic/elasticsearch/pull/51466 [#51466] (issue: http://github.com/elastic/elasticsearch/issues/32299 [#32299])

Geo

 - [x] Handle properly indexing rectangles that crosses the dateline http://github.com/elastic/elasticsearch/pull/53810 [#53810]

Highlighting

 - [x] Fix highlighter support in PinnedQuery and added test http://github.com/elastic/elasticsearch/pull/53716 [#53716] (issue: http://github.com/elastic/elasticsearch/issues/53699 [#53699])

Infra/Core

 - [x] Fix Joda compatibility in stream protocol http://github.com/elastic/elasticsearch/pull/53823 [#53823] (issue: http://github.com/elastic/elasticsearch/issues/53586 [#53586])

 - [x] Avoid self-suppression on grouped action listener http://github.com/elastic/elasticsearch/pull/53262 [#53262] (issue: http://github.com/elastic/elasticsearch/issues/53174 [#53174])

 - [x] Ignore virtual ethernet devices that disappear http://github.com/elastic/elasticsearch/pull/51581 [#51581] (issue: http://github.com/elastic/elasticsearch/issues/49914 [#49914])

 - [x] Fix ingest timezone logic http://github.com/elastic/elasticsearch/pull/51215 [#51215] (issue: http://github.com/elastic/elasticsearch/issues/51108 [#51108])

Infra/Logging

 - [x] Fix LoggingOutputStream to work on windows http://github.com/elastic/elasticsearch/pull/51779 [#51779] (issue: http://github.com/elastic/elasticsearch/issues/51532 [#51532])

Infra/Packaging

 - [x] Handle special characters and spaces in JAVA_HOME path in elasticsearch-service.bat http://github.com/elastic/elasticsearch/pull/52676 [#52676]

 - [x] Limit _FILE env var support to specific vars http://github.com/elastic/elasticsearch/pull/52525 [#52525] (issue: http://github.com/elastic/elasticsearch/issues/52503 [#52503])

 - [x] Always set default ES_PATH_CONF for package scriptlets http://github.com/elastic/elasticsearch/pull/51827 [#51827] (issues: http://github.com/elastic/elasticsearch/issues/50246 [#50246], http://github.com/elastic/elasticsearch/issues/50631 [#50631])

Infra/Plugins

 - [x] Ensure only plugin REST tests are run for plugins http://github.com/elastic/elasticsearch/pull/53184 [#53184] (issues: http://github.com/elastic/elasticsearch/issues/52114 [#52114], http://github.com/elastic/elasticsearch/issues/53183 [#53183])

MULTIPLE AREA LABELS

 - [x] Disallow negative TimeValues http://github.com/elastic/elasticsearch/pull/53913 [#53913] (issue: http://github.com/elastic/elasticsearch/issues/54041 [#54041])

 - [x] Harden search context id http://github.com/elastic/elasticsearch/pull/53143 [#53143]

 - [x] Fix sql cli sourcing of x-pack-env http://github.com/elastic/elasticsearch/pull/52613 [#52613] (issue: http://github.com/elastic/elasticsearch/issues/47803 [#47803])

Machine Learning

 - [x] Do not fail Evaluate API when the actual and predicted fields' types differ http://github.com/elastic/elasticsearch/pull/54255 [#54255] (issue: http://github.com/elastic/elasticsearch/issues/54079 [#54079])

 - [x] [ML] Get ML filters size should default to 100 http://github.com/elastic/elasticsearch/pull/54207 [#54207] (issues: http://github.com/elastic/elasticsearch/issues/39976 [#39976], http://github.com/elastic/elasticsearch/issues/54206 [#54206])

 - [x] [ML] Introduce a "starting" datafeed state for lazy jobs http://github.com/elastic/elasticsearch/pull/53918 [#53918] (issue: http://github.com/elastic/elasticsearch/issues/53763 [#53763])

 - [x] [ML] only retry persistence failures when the failure is intermittent and stop retrying when analytics job is stopping http://github.com/elastic/elasticsearch/pull/53725 [#53725] (issue: http://github.com/elastic/elasticsearch/issues/53687 [#53687])

 - [x] [ML] [Inference] fix number inference models returned in x-pack info API http://github.com/elastic/elasticsearch/pull/53540 [#53540]

 - [x] Make classification evaluation metrics work when there is field mapping type mismatch http://github.com/elastic/elasticsearch/pull/53458 [#53458] (issue: http://github.com/elastic/elasticsearch/issues/53485 [#53485])

 - [x] Perform evaluation in multiple steps when necessary http://github.com/elastic/elasticsearch/pull/53295 [#53295]

 - [x] [ML] specifying missing_field_value value and using it instead of empty_string http://github.com/elastic/elasticsearch/pull/53108 [#53108] (issue: http://github.com/elastic/elasticsearch/issues/1034 [#1034])

 - [x] [ML] Use event.timezone in ingest pipeline from find_file_structure http://github.com/elastic/elasticsearch/pull/52720 [#52720] (issue: http://github.com/elastic/elasticsearch/issues/9458 [#9458])

 - [x] [ML][Inference] don't return inflated definition when storing trained models http://github.com/elastic/elasticsearch/pull/52573 [#52573]

 - [x] [Ml] Validate tree feature index is within range http://github.com/elastic/elasticsearch/pull/52460 [#52460]

 - [x] [ML] Better error when persistent task assignment disabled http://github.com/elastic/elasticsearch/pull/52014 [#52014] (issue: http://github.com/elastic/elasticsearch/issues/51956 [#51956])

 - [x] [ML] Fix possible race condition starting datafeed http://github.com/elastic/elasticsearch/pull/51646 [#51646] (issues: http://github.com/elastic/elasticsearch/issues/50886 [#50886], http://github.com/elastic/elasticsearch/issues/51302 [#51302])

 - [x] [ML] Fix 2 digit year regex in find_file_structure http://github.com/elastic/elasticsearch/pull/51469 [#51469]

 - [x] [ML] Fix possible race condition when starting datafeed http://github.com/elastic/elasticsearch/pull/51302 [#51302] (issue: http://github.com/elastic/elasticsearch/issues/51285 [#51285])

 - [x] [ML] Validate classification dependent_variable cardinality is at lea… http://github.com/elastic/elasticsearch/pull/51232 [#51232]

 - [x] Do not copy mapping from dependent variable to prediction field in regression analysis http://github.com/elastic/elasticsearch/pull/51227 [#51227]

 - [x] [ML] address two edge cases for categorization.GrokPatternCreator#findBestGrokMatchFromExamples http://github.com/elastic/elasticsearch/pull/51168 [#51168]

 - [x] Calculate results and snapshot retention using latest bucket timestamps http://github.com/elastic/elasticsearch/pull/51061 [#51061]

Mapping

 - [x] Disallow duplicate `dynamic_templates` names http://github.com/elastic/elasticsearch/pull/51817 [#51817] (issue: http://github.com/elastic/elasticsearch/issues/28988 [#28988])

 - [x] Throw better exception on wrong `dynamic_templates` syntax http://github.com/elastic/elasticsearch/pull/51783 [#51783] (issue: http://github.com/elastic/elasticsearch/issues/51486 [#51486])

Network

 - [x] Allow proxy mode server name to be updated http://github.com/elastic/elasticsearch/pull/54107 [#54107]

 - [x] Invoke response handler on failure to send http://github.com/elastic/elasticsearch/pull/53631 [#53631]

 - [x] Do not log no-op reconnections at DEBUG http://github.com/elastic/elasticsearch/pull/53469 [#53469]

 - [x] Fix RemoteConnectionManager size() method http://github.com/elastic/elasticsearch/pull/52823 [#52823] (issue: http://github.com/elastic/elasticsearch/issues/52029 [#52029])

 - [x] Remove seeds dependency for remote cluster settings http://github.com/elastic/elasticsearch/pull/52796 [#52796]

 - [x] Add host address to BindTransportException message http://github.com/elastic/elasticsearch/pull/51269 [#51269] (issue: http://github.com/elastic/elasticsearch/issues/48001 [#48001])

Percolator

 - [x] Test percolate queries using `NOW` and sorting http://github.com/elastic/elasticsearch/pull/52758 [#52758] (issues: http://github.com/elastic/elasticsearch/issues/52618 [#52618], http://github.com/elastic/elasticsearch/issues/52748 [#52748])

 - [x] Don't index ranges including NOW in percolator http://github.com/elastic/elasticsearch/pull/52748 [#52748] (issue: http://github.com/elastic/elasticsearch/issues/52617 [#52617])

Reindex

 - [x] Reindex negative TimeValue fix http://github.com/elastic/elasticsearch/pull/54057 [#54057] (issue: http://github.com/elastic/elasticsearch/issues/53913 [#53913])

 - [ ] Reindex: allow comma separated source indices http://github.com/elastic/elasticsearch/pull/52044 [#52044] (issue: http://github.com/elastic/elasticsearch/issues/51949 [#51949])

SQL

 - [x] SQL: Fix NPE for parameterized LIKE/RLIKE http://github.com/elastic/elasticsearch/pull/53573 [#53573] (issue: http://github.com/elastic/elasticsearch/issues/53557 [#53557])

 - [x] SQL: add support for index aliases for SYS COLUMNS command http://github.com/elastic/elasticsearch/pull/53525 [#53525] (issue: http://github.com/elastic/elasticsearch/issues/31609 [#31609])

 - [x] SQL: Fix issue with LIKE/RLIKE as painless script http://github.com/elastic/elasticsearch/pull/53495 [#53495] (issue: http://github.com/elastic/elasticsearch/issues/53486 [#53486])

 - [x] SQL: Fix column size for IP data type http://github.com/elastic/elasticsearch/pull/53056 [#53056] (issue: http://github.com/elastic/elasticsearch/issues/52762 [#52762])

 - [x] SQL: supplement input checks on received request parameters http://github.com/elastic/elasticsearch/pull/52229 [#52229]

 - [x] SQL: Fix issue with timezone when paginating http://github.com/elastic/elasticsearch/pull/52101 [#52101] (issue: http://github.com/elastic/elasticsearch/issues/51258 [#51258])

 - [x] SQL: Fix ORDER BY on aggregates and GROUPed BY fields http://github.com/elastic/elasticsearch/pull/51894 [#51894] (issue: http://github.com/elastic/elasticsearch/issues/50355 [#50355])

 - [x] SQL: Fix milliseconds handling in intervals http://github.com/elastic/elasticsearch/pull/51675 [#51675] (issue: http://github.com/elastic/elasticsearch/issues/41635 [#41635])

 - [x] SQL: Fix ORDER BY YEAR() function http://github.com/elastic/elasticsearch/pull/51562 [#51562] (issue: http://github.com/elastic/elasticsearch/issues/51224 [#51224])

 - [x] SQL: change the way unsupported data types fields are handled http://github.com/elastic/elasticsearch/pull/50823 [#50823]

 - [x] SQL: selecting a literal from grouped by query generates error http://github.com/elastic/elasticsearch/pull/41964 [#41964] (issues: http://github.com/elastic/elasticsearch/issues/41413 [#41413], http://github.com/elastic/elasticsearch/issues/41951 [#41951])

Search

 - [x] Fix Term Vectors with artificial docs and keyword fields http://github.com/elastic/elasticsearch/pull/53504 [#53504] (issue: http://github.com/elastic/elasticsearch/issues/53494 [#53494])

 - [x] Fix concurrent requests race over scroll context limit http://github.com/elastic/elasticsearch/pull/53449 [#53449]

 - [x] Fix pre-sorting of shards in the can_match phase http://github.com/elastic/elasticsearch/pull/53397 [#53397]

 - [x] Fix potential NPE in FuzzyTermsEnum http://github.com/elastic/elasticsearch/pull/53231 [#53231] (issue: http://github.com/elastic/elasticsearch/issues/52894 [#52894])

 - [x] Fix inaccurate total hit count in _search/template api http://github.com/elastic/elasticsearch/pull/53155 [#53155] (issue: http://github.com/elastic/elasticsearch/issues/52801 [#52801])

 - [x] Correct boost in script_score query and error on negative scores http://github.com/elastic/elasticsearch/pull/52478 [#52478] (issue: http://github.com/elastic/elasticsearch/issues/48465 [#48465])

Snapshot/Restore

 - [x] Fix Non-Verbose Snapshot List Missing Empty Snapshots http://github.com/elastic/elasticsearch/pull/52433 [#52433]

 - [x] Fix Inconsistent Shard Failure Count in Failed Snapshots http://github.com/elastic/elasticsearch/pull/51416 [#51416] (issue: http://github.com/elastic/elasticsearch/issues/47550 [#47550])

 - [x] Fix Overly Aggressive Request DeDuplication http://github.com/elastic/elasticsearch/pull/51270 [#51270] (issue: http://github.com/elastic/elasticsearch/issues/51253 [#51253])

Store

 - [x] Fix synchronization in ByteSizeCachingDirectory http://github.com/elastic/elasticsearch/pull/52512 [#52512]

Transform

 - [x] [Transform] Transform optmize date histogram http://github.com/elastic/elasticsearch/pull/54068 [#54068] (issue: http://github.com/elastic/elasticsearch/issues/54254 [#54254])

 - [x] [Transform] fix NPE in derive stats if shouldStopAtNextCheckpoint is set http://github.com/elastic/elasticsearch/pull/52940 [#52940]

 - [x] [Transform] Fix mapping deduction for scaled_float http://github.com/elastic/elasticsearch/pull/51990 [#51990] (issue: http://github.com/elastic/elasticsearch/issues/51780 [#51780])

 - [x] [Transform] Fix stats can return old state information if security is enabled http://github.com/elastic/elasticsearch/pull/51732 [#51732] (issue: http://github.com/elastic/elasticsearch/issues/51728 [#51728])

**Comment by codebrain** [comment]
Merged into https://github.com/elastic/elasticsearch-net/issues/4525
