### ISSUE TITLE
7.7.1 meta ticket

### ISSUE THREAD

**Issue by codebrain** [elastic/elasticsearch-net#4610]
## New APIS (bumped from 7.7.0)

 - [x] async_search.delete.json
 - [x] async_search.get.json
 - [x] async_search.submit.json
 - [x] transform.delete_transform.json
 - [x] transform.get_transform.json
 - [x] transform.get_transform_stats.json
 - [x] transform.preview_transform.json
 - [x] transform.put_transform.json
 - [x] transform.start_transform.json
 - [x] transform.stop_transform.json
 - [x] transform.update_transform.json

**Comment by russcam** [comment]
Closing as 7.7.1 is released
