### ISSUE TITLE
7.8.0 Meta ticket

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#4718]
This meta ticket tracks the changes in Elasticsearch 7.8.0 that require changes in the client:

### New APIs

- [x] Cluster Delete VotingConfigExclusions 
- [x] Cluster Post VotingConfigExclusions 

#### Cluster Coordination
- [x] Voting config exclusions should work with absent nodes [#50836](https://github.com/elastic/elasticsearch/pull/50836) (issue: [#47990](https://github.com/elastic/elasticsearch/issues/47990))

#### Infra/Core
- [x] Deprecate node local storage setting [#54374](https://github.com/elastic/elasticsearch/pull/54374)

#### Aggregations

- [x] Add support for filters to T-Test aggregation [#54980](https://github.com/elastic/elasticsearch/pull/54980) (issue: [#53692](https://github.com/elastic/elasticsearch/issues/53692))
- [x] Add Student's t-test aggregation support [#54469](https://github.com/elastic/elasticsearch/pull/54469) (issue: [#53692](https://github.com/elastic/elasticsearch/issues/53692))

#### Features/Indices APIs
- ~[ ] Add simulate template composition API _index_template/_simulate_index/{name}  [#55686](https://github.com/elastic/elasticsearch/pull/55686) (issue: [#53101](https://github.com/elastic/elasticsearch/issues/53101))~ Simulate index template APIs are experimental

#### Geo

- [x] Add new point field. [#53804](https://github.com/elastic/elasticsearch/pull/53804)

#### Aggregations
- [x] Expose agg usage in Feature Usage API [#55732](https://github.com/elastic/elasticsearch/pull/55732) (issue: [#53746](https://github.com/elastic/elasticsearch/issues/53746))

#### Analysis
- [x] Add preserve_original setting in ngram token filter [#55432](https://github.com/elastic/elasticsearch/pull/55432)

#### Cluster Coordination
- [x] Add voting config exclusion add and clear API spec and integration test cases [#55760](https://github.com/elastic/elasticsearch/pull/55760) (issue: [#48131](https://github.com/elastic/elasticsearch/issues/48131))

#### Features/CAT APIs
- ~[ ] Add support for V2 index templates to /_cat/templates [#55829](https://github.com/elastic/elasticsearch/pull/55829) (issue: [#53101](https://github.com/elastic/elasticsearch/issues/53101))~ v2 index template APIs are experimental

#### Features/Indices APIs

- ~[ ] Update template v2 api rest spec [#55948](https://github.com/elastic/elasticsearch/pull/55948) (issue: [#53101](https://github.com/elastic/elasticsearch/issues/53101))~ v2 index template APIs are experimental
- ~[ ] Add prefer_v2_templates flag and index setting [#55411](https://github.com/elastic/elasticsearch/pull/55411) (issue: [#53101](https://github.com/elastic/elasticsearch/issues/53101))~ v2 index template APIs are experimental

#### Features/Stats
- ~[ ] Add Bulk stats track the bulk per shard [#52208](https://github.com/elastic/elasticsearch/pull/52208) (issues: [#47345](https://github.com/elastic/elasticsearch/issues/47345), [#50536](https://github.com/elastic/elasticsearch/issues/50536))~ Doesn't look to be in 7.8. See https://github.com/elastic/elasticsearch/pull/52208#issuecomment-640999720

#### Geo
- [x] Doc values support for geo shapes. [ISSUE] [#37206](https://github.com/elastic/elasticsearch/pull/37206). NEST already implements `doc_values` for `GeoShapeProperty`

#### Infra/REST API
- ~[ ] Add validation to the usage service [#54617](https://github.com/elastic/elasticsearch/pull/54617)~ no client changes required

#### Infra/Scripting
- [x] Scripting: stats per context in nodes stats [#54008](https://github.com/elastic/elasticsearch/pull/54008) (issue: [#50152](https://github.com/elastic/elasticsearch/issues/50152))

#### MULTIPLE AREA LABELS

- [x] Add geo_shape mapper supporting doc-values in Spatial Plugin [#55037](https://github.com/elastic/elasticsearch/pull/55037) (issue: [#53562](https://github.com/elastic/elasticsearch/issues/53562))
- ~[ ] Add pre-configured “lowercase” normalizer [#53882](https://github.com/elastic/elasticsearch/pull/53882) (issue: [#53872](https://github.com/elastic/elasticsearch/issues/53872))~ No client changes required

#### Snapshot/Restore

- ~[ ] Allow Deleting Multiple Snapshots at Once [#55474](https://github.com/elastic/elasticsearch/pull/55474)~ Change has been made to REST spec in master (https://github.com/elastic/elasticsearch/pull/57326), but change will not be ported to 7.x

#### Transform
- [x] [Transform] add throttling [#56007](https://github.com/elastic/elasticsearch/pull/56007) (issue: [#54862](https://github.com/elastic/elasticsearch/issues/54862))

#### Aggregations

- [x] Add analytics plugin usage stats to _xpack/usage [#54911](https://github.com/elastic/elasticsearch/pull/54911) (issue: [#54847](https://github.com/elastic/elasticsearch/issues/54847))

#### Analysis

- [x] Add preserve_original setting in edge ngram token filter [#55766](https://github.com/elastic/elasticsearch/pull/55766) (issue: [#55767](https://github.com/elastic/elasticsearch/issues/55767))

#### Features/Ingest

- [x] Fix empty_value handling in CsvProcessor [#55649](https://github.com/elastic/elasticsearch/pull/55649) (issue: [#55643](https://github.com/elastic/elasticsearch/issues/55643))

**Comment by russcam** [comment]
Superseded by https://github.com/elastic/elasticsearch-net/issues/4803
