### ISSUE TITLE
7.8.1 Meta ticket

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#4803]
Remaining items from 7.8.0 Meta ticket #4718 

#### Machine Learning
- [x] [ML] More advanced model snapshot retention options [#56125](https://github.com/elastic/elasticsearch/pull/56125) (issue: [#52150](https://github.com/elastic/elasticsearch/issues/52150))
- [x] [ML] Adding failed_category_count to model_size_stats [#55716](https://github.com/elastic/elasticsearch/pull/55716) (issue: [#1130](https://github.com/elastic/elasticsearch/issues/1130))
- [x] [ML] Add effective max model memory limit to ML info [#55529](https://github.com/elastic/elasticsearch/pull/55529) (issue: [#63942](https://github.com/elastic/elasticsearch/issues/63942))
- [x] [ML] Return assigned node in start/open job/datafeed response [#55473](https://github.com/elastic/elasticsearch/pull/55473) (issue: [#54067](https://github.com/elastic/elasticsearch/issues/54067))
- ~[ ] [ML] adding prediction_field_type to inference config [#55128](https://github.com/elastic/elasticsearch/pull/55128)~ Relates to classification which is experimental.
- ~[ ] [ML] add new inference_config field to trained model config [#54421](https://github.com/elastic/elasticsearch/pull/54421)~ Relates to inference which is still an experimental feature.

**Comment by russcam** [comment]
Closing this as 7.8.1 is released
