### ISSUE TITLE
7.9.0 Meta ticket

### ISSUE THREAD

**Issue by russcam** [elastic/elasticsearch-net#4872]
#### Features/Ingest
- [x] Add optional description parameter to ingest processors. [#57906](https://github.com/elastic/elasticsearch/pull/57906) (issue: [#56000](https://github.com/elastic/elasticsearch/issues/56000))

#### Aggregations
- [x] Add Normalize Pipeline Aggregation [#56399](https://github.com/elastic/elasticsearch/pull/56399) (issue: [#51005](https://github.com/elastic/elasticsearch/issues/51005))
- ~[ ] Add Variable Width Histogram Aggregation [#42035](https://github.com/elastic/elasticsearch/pull/42035) (issues: [#9572](https://github.com/elastic/elasticsearch/issues/9572), [#50863](https://github.com/elastic/elasticsearch/issues/50863))~ Experimental: see https://github.com/elastic/elasticsearch/issues/58573
- [x] Add moving percentiles pipeline aggregation [#55441](https://github.com/elastic/elasticsearch/pull/55441) (issue: [#49452](https://github.com/elastic/elasticsearch/issues/49452))

#### MULTIPLE AREA LABELS
~- [ ] Pipeline Inference Aggregation [#58193](https://github.com/elastic/elasticsearch/pull/58193)~ inference still an experimental feature.

#### Machine Learning
~- [ ] Introduce DataFrameAnalyticsConfig update API [#58302](https://github.com/elastic/elasticsearch/pull/58302) (issue: [#45720](https://github.com/elastic/elasticsearch/issues/45720))~ inference still an experimental feature.
- [x] Introduce ModelPlotConfig.annotations_enabled setting [#57539](https://github.com/elastic/elasticsearch/pull/57539) (issue: [#55781](https://github.com/elastic/elasticsearch/issues/55781))

#### Mapping
- [x] Wildcard field optimised for wildcard queries [#49993](https://github.com/elastic/elasticsearch/pull/49993) (issue: [#48852](https://github.com/elastic/elasticsearch/issues/48852))

#### Search
- [x] Allow index filtering in field capabilities API [#57276](https://github.com/elastic/elasticsearch/pull/57276) (issue: [#56195](https://github.com/elastic/elasticsearch/issues/56195))

#### Aggregations
- [x] Add support for numeric range keys [#56452](https://github.com/elastic/elasticsearch/pull/56452) (issue: [#56402](https://github.com/elastic/elasticsearch/issues/56402))

- [x] Added standard deviation / variance sampling to extended stats [#49782](https://github.com/elastic/elasticsearch/pull/49782) (issue: [#49554](https://github.com/elastic/elasticsearch/issues/49554))

#### Allocation
- [x] Account for remaining recovery in disk allocator [#58029](https://github.com/elastic/elasticsearch/pull/58029)

#### Analysis
- [x] Add max_token_length setting to the CharGroupTokenizer [#56860](https://github.com/elastic/elasticsearch/pull/56860) (issue: [#56676](https://github.com/elastic/elasticsearch/issues/56676))
- [x] Expose discard_compound_token option to kuromoji_tokenizer [#57421](https://github.com/elastic/elasticsearch/pull/57421)
~- [ ] Support multiple tokens on LHS in stemmer_override rules (#56113) [#56484](https://github.com/elastic/elasticsearch/pull/56484) (issue: [#56113](https://github.com/elastic/elasticsearch/issues/56113))~ No client change needed

#### Authorization
- [x] Add cache for application privileges [#55836](https://github.com/elastic/elasticsearch/pull/55836) (issue: [#54317](https://github.com/elastic/elasticsearch/issues/54317))

#### CCR
- [x] Allow follower indices to override leader settings [#58103](https://github.com/elastic/elasticsearch/pull/58103)

#### Features/Indices APIs

- [x] Add index block api [#58094](https://github.com/elastic/elasticsearch/pull/58094)
- [x] Add new flag to check whether alias exists on remove [#58100](https://github.com/elastic/elasticsearch/pull/58100)

#### Features/Ingest
- [x] Add ignore_empty_value parameter in set ingest processor [#57030](https://github.com/elastic/elasticsearch/pull/57030) (issue: [#54783](https://github.com/elastic/elasticsearch/issues/54783))
- [x] Support `if_seq_no` and `if_primary_term` for ingest [#55430](https://github.com/elastic/elasticsearch/pull/55430) (issue: [#41255](https://github.com/elastic/elasticsearch/issues/41255))

#### Machine Learning
~- [ ] Adds new for_export flag to GET _ml/inference API [#57351](https://github.com/elastic/elasticsearch/pull/57351)~ inference is still an experiemental feature

~- [ ] Calculate cache misses for inference and return in stats [#58252](https://github.com/elastic/elasticsearch/pull/58252)~ inference is still an experiemental feature

- [x] Delete expired data by job [#57337](https://github.com/elastic/elasticsearch/pull/57337)

~- [ ] Introduce Annotation.event field [#57144](https://github.com/elastic/elasticsearch/pull/57144) (issue: [#55781](https://github.com/elastic/elasticsearch/issues/55781))~ No client change needed

#### Mapping
- [x] Add regex query support to wildcard field (approach 2) [#55548](https://github.com/elastic/elasticsearch/pull/55548) (issue: [#54725](https://github.com/elastic/elasticsearch/issues/54725))
- [x] Make `keyword` a family of field types [#58315](https://github.com/elastic/elasticsearch/pull/58315) (issue: [#53175](https://github.com/elastic/elasticsearch/issues/53175))

- [x] Support null_value for wildcard field type. [ISSUE] [#55701](https://github.com/elastic/elasticsearch/pull/55701)
- [x] Wildcard field - add support for custom null values [#57047](https://github.com/elastic/elasticsearch/pull/57047)

#### Recovery
- [x] Implement dangling indices API [#50920](https://github.com/elastic/elasticsearch/pull/50920) (issue: [#48366](https://github.com/elastic/elasticsearch/issues/48366))

#### Search
- [x] Add description to submit and get async search, as well as cancel tasks [#57745](https://github.com/elastic/elasticsearch/pull/57745)
- [x] Add range query support to wildcard field [#57881](https://github.com/elastic/elasticsearch/pull/57881) (issue: [#57816](https://github.com/elastic/elasticsearch/issues/57816))
- [x] Specify reason whenever async search gets cancelled [#57761](https://github.com/elastic/elasticsearch/pull/57761)

#### Transform
- [x] Add support for terms agg in transforms [#56696](https://github.com/elastic/elasticsearch/pull/56696)
- [x] Adds geotile_grid support in group_by [#56514](https://github.com/elastic/elasticsearch/pull/56514) (issue: [#56121](https://github.com/elastic/elasticsearch/issues/56121))

#### Mapping
- [x] Wildcard field fix for scripts - changed value type from BytesRef to String  [#58060](https://github.com/elastic/elasticsearch/pull/58060) (issue: [#58044](https://github.com/elastic/elasticsearch/issues/58044))

**Comment by russcam** [comment]
Closing as all items are checked
