### ISSUE TITLE
7.10.1 Meta Ticket

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elasticsearch-net#5096]
### **Breaking Java changes**

**Machine Learning**

- [ ] Deprecate allow_no_jobs and allow_no_datafeeds in favor of allow_no_match [#60601](https://github.com/elastic/elasticsearch/pull/60601) (issue: [#60642](https://github.com/elastic/elasticsearch/issues/60642))

### **Deprecations**

*Cluster Coordination**

~~- [ ] Deprecate and ignore join timeout [#60872](https://github.com/elastic/elasticsearch/pull/60872) (issue: [#60873](https://github.com/elastic/elasticsearch/issues/60873))~~

### **New features**

**Aggregations**

- [ ] Add rate aggregation [#61369](https://github.com/elastic/elasticsearch/pull/61369) (issue: [#60674](https://github.com/elastic/elasticsearch/issues/60674))

**Features/Features**

- [ ] Add data tiers (hot, warm, cold, frozen) as custom node roles [#60994](https://github.com/elastic/elasticsearch/pull/60994) (issue: [#60848](https://github.com/elastic/elasticsearch/issues/60848))

**Features/ILM+SLM**

- [ ] ILM migrate data between tiers [#61377](https://github.com/elastic/elasticsearch/pull/61377) (issue: [#60848](https://github.com/elastic/elasticsearch/issues/60848))
- [ ] ILM: add force-merge step to searchable snapshots action [#60819](https://github.com/elastic/elasticsearch/pull/60819) (issues: [#53488](https://github.com/elastic/elasticsearch/issues/53488), [#56215](https://github.com/elastic/elasticsearch/issues/56215))

**Machine Learning**

- [ ] Implement AucRoc metric for classification [#60502](https://github.com/elastic/elasticsearch/pull/60502) (issue: [#62160](https://github.com/elastic/elasticsearch/issues/62160))

**Mapping**

- [ ] Introduce 64-bit unsigned long field type [#60050](https://github.com/elastic/elasticsearch/pull/60050) (issue: [#32434](https://github.com/elastic/elasticsearch/issues/32434))

**Search**

- [ ] Add search _fields_ option to support high-level field retrieval [#60100](https://github.com/elastic/elasticsearch/pull/60100) (issues: [#49028](https://github.com/elastic/elasticsearch/issues/49028), [#55363](https://github.com/elastic/elasticsearch/issues/55363))

### **Enhancements**

**Aggregations**

- [x] Adds hard_bounds to histogram aggregations [#59175](https://github.com/elastic/elasticsearch/pull/59175) (issue: [#50109](https://github.com/elastic/elasticsearch/issues/50109))

**Analysis**

- [x] Support ignore_keywords flag for word delimiter graph token filter [#59563](https://github.com/elastic/elasticsearch/pull/59563) (issue: [#59491](https://github.com/elastic/elasticsearch/issues/59491))

**Authentication**

- [x] Include authentication type for the authenticate response [#61247](https://github.com/elastic/elasticsearch/pull/61247) (issue: [#61130](https://github.com/elastic/elasticsearch/issues/61130))
- [ ] Oidc additional client auth types [#58708](https://github.com/elastic/elasticsearch/pull/58708)

**Authorization**

- [ ] Add more context to index access denied errors [#60357](https://github.com/elastic/elasticsearch/pull/60357) (issue: [#42166](https://github.com/elastic/elasticsearch/issues/42166))

**CRUD**

- [x] Add configured indexing memory limit to node stats [#60342](https://github.com/elastic/elasticsearch/pull/60342)
- [ ] Dedicated threadpool for system index writes [#61655](https://github.com/elastic/elasticsearch/pull/61655)

**Cluster Coordination**

- [ ] Provide option to allow writes when master is down [#60605](https://github.com/elastic/elasticsearch/pull/60605)

**Distributed**

- [ ] Detect noop of update index settings [#61348](https://github.com/elastic/elasticsearch/pull/61348)

**Features/CAT APIs**

- [x] Adding Hit counts and Miss counts for QueryCache exposed through REST API [#60114](https://github.com/elastic/elasticsearch/pull/60114) (issue: [#48645](https://github.com/elastic/elasticsearch/issues/48645))

**Features/Features**

- [ ] Add aggregation list to node info [#60074](https://github.com/elastic/elasticsearch/pull/60074) (issue: [#52057](https://github.com/elastic/elasticsearch/issues/52057))
- [ ] Adding new `require_alias` option to indexing requests [#58917](https://github.com/elastic/elasticsearch/pull/58917) (issue: [#55267](https://github.com/elastic/elasticsearch/issues/55267))

**Features/Ingest**

- [ ] Add network from MaxMind Geo ASN database [#61676](https://github.com/elastic/elasticsearch/pull/61676)
- [ ] Allow_duplicates option for append processor [#61916](https://github.com/elastic/elasticsearch/pull/61916) (issue: [#57543](https://github.com/elastic/elasticsearch/issues/57543))
- [ ] Configurable output format for date processor [#61324](https://github.com/elastic/elasticsearch/pull/61324) (issue: [#42523](https://github.com/elastic/elasticsearch/issues/42523))
- [ ] Enhance the ingest node simulate verbose output [#60433](https://github.com/elastic/elasticsearch/pull/60433) (issue: [#56004](https://github.com/elastic/elasticsearch/issues/56004))
- [ ] Per processor description for verbose simulate [#58207](https://github.com/elastic/elasticsearch/pull/58207) (issue: [#57906](https://github.com/elastic/elasticsearch/issues/57906))
- [ ] Preserve grok pattern ordering and add sort option [#61671](https://github.com/elastic/elasticsearch/pull/61671) (issue: [#40819](https://github.com/elastic/elasticsearch/issues/40819))

**Infra/Core**

- [ ] Add logstash system index APIs [#53350](https://github.com/elastic/elasticsearch/pull/53350)
- [ ] Deprecate REST access to System Indices [#60945](https://github.com/elastic/elasticsearch/pull/60945)

**Infra/Logging**

- [ ] Write deprecation logs to a data stream [#61484](https://github.com/elastic/elasticsearch/pull/61484) (issues: [#46106](https://github.com/elastic/elasticsearch/issues/46106), [#61474](https://github.com/elastic/elasticsearch/issues/61474))

**Machine Learning**

- [ ] Add a "verbose" option to the data frame analytics stats endpoint [#59589](https://github.com/elastic/elasticsearch/pull/59589) (issue: [#59125](https://github.com/elastic/elasticsearch/issues/59125))
- [ ] Add new include flag to get trained models API for model training metadata [#61922](https://github.com/elastic/elasticsearch/pull/61922)
- [ ] Add new feature_processors field for data frame analytics [#60528](https://github.com/elastic/elasticsearch/pull/60528) (issue: [#59327](https://github.com/elastic/elasticsearch/issues/59327))
- [ ] Add new n_gram_encoding custom processor [#61578](https://github.com/elastic/elasticsearch/pull/61578)
- [ ] Calculate total feature importance to store with model metadata [#1387](https://github.com/elastic/ml-cpp/pull/1387)
- [ ] Change outlier detection feature_influence format to array with nested objects [#1475](https://github.com/elastic/ml-cpp/pull/1475), [#62068](https://github.com/elastic/elasticsearch/pull/62068)

**Mapping**

- [ ] Add field type for version strings [#59773](https://github.com/elastic/elasticsearch/pull/59773) (issue: [#48878](https://github.com/elastic/elasticsearch/issues/48878))
- [ ] Allow [null] values in [null_value] [#61798](https://github.com/elastic/elasticsearch/pull/61798) (issues: [#7978](https://github.com/elastic/elasticsearch/issues/7978), [#58823](https://github.com/elastic/elasticsearch/issues/58823))
- [ ] Allow metadata fields in the _source [#61590](https://github.com/elastic/elasticsearch/pull/61590) (issue: [#58339](https://github.com/elastic/elasticsearch/issues/58339))

**Search**

- [x] Introduce point in time APIs in x-pack basic [#61062](https://github.com/elastic/elasticsearch/pull/61062) (issues: [#26472](https://github.com/elastic/elasticsearch/issues/26472), [#46523](https://github.com/elastic/elasticsearch/issues/46523))
- [ ] Add case insensitive flag for "term" family of queries [#61596](https://github.com/elastic/elasticsearch/pull/61596) (issue: [#61546](https://github.com/elastic/elasticsearch/issues/61546))
- [ ] Add case insensitive support for regex queries [#59441](https://github.com/elastic/elasticsearch/pull/59441)
- [ ] Tweak toXContent implementation of ParametrizedFieldMapper [#59968](https://github.com/elastic/elasticsearch/pull/59968)
- [ ] Implement fields value fetching for the `text`, `search_as_you_type` and `token_count` field types [#63515](https://github.com/elastic/elasticsearch/pull/63515)

**Snapshot/Restore**

- [ ] Add repositories metering API [#60371](https://github.com/elastic/elasticsearch/pull/60371)
- [ ] Clone Snapshot API [#61839](https://github.com/elastic/elasticsearch/pull/61839)
- [ ] Introduce index based snapshot blob cache for Searchable Snapshots [#60522](https://github.com/elastic/elasticsearch/pull/60522)

**Store**

- [ ] Report more details of unobtainable ShardLock [#61255](https://github.com/elastic/elasticsearch/pull/61255) (issue: [#38807](https://github.com/elastic/elasticsearch/issues/38807))

**Transform**

- [ ] Add support for missing bucket [#59591](https://github.com/elastic/elasticsearch/pull/59591) (issues: [#42941](https://github.com/elastic/elasticsearch/issues/42941), [#55102](https://github.com/elastic/elasticsearch/issues/55102))

### **Bug fixes**

**Aggregations**

- [ ] Fix AOOBE when setting min_doc_count to 0 in significant_terms [#60823](https://github.com/elastic/elasticsearch/pull/60823) (issues: [#60683](https://github.com/elastic/elasticsearch/issues/60683), [#60824](https://github.com/elastic/elasticsearch/issues/60824))
- [ ] Make sure non-collecting aggs include sub-aggs [#64214](https://github.com/elastic/elasticsearch/pull/64214) (issue: [#64142](https://github.com/elastic/elasticsearch/issues/64142))
- [ ] Fix broken parent and child aggregator [#63811](https://github.com/elastic/elasticsearch/pull/63811)

**Authorization**

~~- [ ] Report anonymous roles in authenticate response [#61355](https://github.com/elastic/elasticsearch/pull/61355) (issues: [#47195](https://github.com/elastic/elasticsearch/issues/47195), [#53453](https://github.com/elastic/elasticsearch/issues/53453), [#57711](https://github.com/elastic/elasticsearch/issues/57711), [#57853](https://github.com/elastic/elasticsearch/issues/57853))~~

**CRUD**

- [ ] Propagate forceExecution when acquiring permit [#60634](https://github.com/elastic/elasticsearch/pull/60634) (issue: [#60359](https://github.com/elastic/elasticsearch/issues/60359))

**Distributed**

- [ ] Fix cluster health when closing [#61709](https://github.com/elastic/elasticsearch/pull/61709)

**Features/Stats**

- [ ] Remove sporadic min/max usage estimates from stats [#59755](https://github.com/elastic/elasticsearch/pull/59755)

**Features/Watcher**

- [ ] Correct the query dsl for watching elasticsearch version [#58321](https://github.com/elastic/elasticsearch/pull/58321) (issue: [#58261](https://github.com/elastic/elasticsearch/issues/58261))
- [ ] Fix passing params to template or script failed in watcher [#58559](https://github.com/elastic/elasticsearch/pull/58559) (issue: [#57625](https://github.com/elastic/elasticsearch/issues/57625))

**Machine Learning**

- [ ] Get data frame analytics jobs stats API can return multiple responses if more than one error [#60900](https://github.com/elastic/elasticsearch/pull/60900) (issue: [#60876](https://github.com/elastic/elasticsearch/issues/60876))
- [ ] Correct the anomaly detection job model state `min_version` [#1546](https://github.com/elastic/ml-cpp/pull/1546)

**Mapping**

- [ ] Improve _ignore_malformed_ handling for dates [#60211](https://github.com/elastic/elasticsearch/pull/60211) (issue: [#52634](https://github.com/elastic/elasticsearch/issues/52634))

**Network**

- [ ] Suppress noisy SSL exceptions [#61359](https://github.com/elastic/elasticsearch/pull/61359)

**Search**

- [ ] Allows nanosecond resolution in search_after [#60328](https://github.com/elastic/elasticsearch/pull/60328) (issue: [#52424](https://github.com/elastic/elasticsearch/issues/52424))

**Comment by stevejgordon** [comment]
Closing with remaining items included in #5198
