### ISSUE TITLE
7.11.0 Meta Ticket

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elasticsearch-net#5198]
### Breaking changes

**Machine Learning**

- [x]   Add new flag exclude_generated that removes generated fields in GET config APIs [#63899](https://github.com/elastic/elasticsearch/pull/63899) (issue: [#63055](https://github.com/elastic/elasticsearch/issues/63055))

### Deprecations

**Features/CAT APIs**

- [x]   Deprecate the 'local' parameter of /_cat/indices [#62198](https://github.com/elastic/elasticsearch/pull/62198) (issue: [#60718](https://github.com/elastic/elasticsearch/issues/60718))
- [x]   Deprecate the 'local' parameter of /_cat/shards [#62197](https://github.com/elastic/elasticsearch/pull/62197) (issue: [#60718](https://github.com/elastic/elasticsearch/issues/60718))

**MULTIPLE AREA LABELS**

- [x]   Deprecates _upgrade API (#47678) [#50484](https://github.com/elastic/elasticsearch/pull/50484) (issue: [#47678](https://github.com/elastic/elasticsearch/issues/47678))

**Mapping**

- [ ] ~~Emit a warning when an unknown geo strategy is passed in [#63975](https://github.com/elastic/elasticsearch/pull/63975)~~

### New features

**Aggregations**

- [ ]   Support global ords in top_metrics [#64967](https://github.com/elastic/elasticsearch/pull/64967) (issue: [#64774](https://github.com/elastic/elasticsearch/issues/64774))

**Features/Ingest**

- [x] URI parts ingest processor [#65150](https://github.com/elastic/elasticsearch/pull/65150) (issue: [#57481](https://github.com/elastic/elasticsearch/issues/57481)) - **PR #5304**

**Geo**

- [x]   Add geo_line aggregation [#41612](https://github.com/elastic/elasticsearch/pull/41612) (issue: [#41649](https://github.com/elastic/elasticsearch/issues/41649))

**MULTIPLE AREA LABELS**

- [ ]   Add doc_count field mapper [#64503](https://github.com/elastic/elasticsearch/pull/64503) (issue: [#58339](https://github.com/elastic/elasticsearch/issues/58339))

**Search**

- [x]   Async search status API [#62947](https://github.com/elastic/elasticsearch/pull/62947) (issue: [#57537](https://github.com/elastic/elasticsearch/issues/57537)) - **PR #5239**

### Enhancements

**Aggregations**

- [ ]   Add hard_bounds support for histogram field-based histograms [#64246](https://github.com/elastic/elasticsearch/pull/64246) (issue: [#62124](https://github.com/elastic/elasticsearch/issues/62124))
- [x]   Add support for histogram fields to rate aggregation [#63289](https://github.com/elastic/elasticsearch/pull/63289) (issue: [#62939](https://github.com/elastic/elasticsearch/issues/62939)) - **PR #5206**
- [x]   Add supports for upper and lower values on boxplot based on the IQR value [#63617](https://github.com/elastic/elasticsearch/pull/63617) (issue: [#60466](https://github.com/elastic/elasticsearch/issues/60466))
- [x]   Add value_count mode to rate agg [#63687](https://github.com/elastic/elasticsearch/pull/63687) (issue: [#63575](https://github.com/elastic/elasticsearch/issues/63575)) - **PR #5206**
- [ ]   Allow mixing set-based and regexp-based include and exclude [#63325](https://github.com/elastic/elasticsearch/pull/63325) (issue: [#62246](https://github.com/elastic/elasticsearch/issues/62246))

**Authentication**

- [ ]   Adding API for generating SAML SP metadata [#64517](https://github.com/elastic/elasticsearch/pull/64517) (issue: [#49018](https://github.com/elastic/elasticsearch/issues/49018))
- [ ]   Adds realm name OIDC _security/oidc/prepare and _security/oidc/authenticate APIs responses [#64966](https://github.com/elastic/elasticsearch/pull/64966) (issue: [#53161](https://github.com/elastic/elasticsearch/issues/53161))

**Client**

- [ ]   Adding authentication information to access token create APIs [#62490](https://github.com/elastic/elasticsearch/pull/62490) (issue: [#59685](https://github.com/elastic/elasticsearch/issues/59685))

**Features/Data streams**

- [ ]   Add custom metadata support to data steams. [#63991](https://github.com/elastic/elasticsearch/pull/63991) (issue: [#59195](https://github.com/elastic/elasticsearch/issues/59195))
- [ ]   Hidden data streams [#63987](https://github.com/elastic/elasticsearch/pull/63987) (issue: [#63889](https://github.com/elastic/elasticsearch/issues/63889))
- [ ]   REST endpoint and tests for data stream migration [#64415](https://github.com/elastic/elasticsearch/pull/64415) (issue: [#61046](https://github.com/elastic/elasticsearch/issues/61046))

**Features/Indices APIs**

- [ ]   Add a template parameter to override auto_create_index value [#61858](https://github.com/elastic/elasticsearch/pull/61858) (issue: [#20640](https://github.com/elastic/elasticsearch/issues/20640))
- [ ]   Mark component and composable index template APIs as stable [#65013](https://github.com/elastic/elasticsearch/pull/65013)

**Features/Ingest**

- [ ]   Add copy_from parameter for set ingest processor [#63540](https://github.com/elastic/elasticsearch/pull/63540) (issues: [#51046](https://github.com/elastic/elasticsearch/issues/51046), [#55682](https://github.com/elastic/elasticsearch/issues/55682), [#56985](https://github.com/elastic/elasticsearch/issues/56985))
- [x]   Attachment ingest processor: add resource_name field [#64389](https://github.com/elastic/elasticsearch/pull/64389) - **PR AWAITING APPROVAL #5205** 

**Geo**

- [ ]   Enable geo_distance and geo_bounding_box queries on geo_shape field type [#64224](https://github.com/elastic/elasticsearch/pull/64224) (issue: [#54628](https://github.com/elastic/elasticsearch/issues/54628))

**License**

- [x]   Adding a warning header when a license is about to expire [#64948](https://github.com/elastic/elasticsearch/pull/64948) (issue: [#60562](https://github.com/elastic/elasticsearch/issues/60562))

**MULTIPLE AREA LABELS**

- [ ]   Do not skip not available shard exception in search response [#64337](https://github.com/elastic/elasticsearch/pull/64337) (issue: [#47700](https://github.com/elastic/elasticsearch/issues/47700))
- [ ]   Check Security Roles in Deprecation Info API [#49212](https://github.com/elastic/elasticsearch/pull/49212) (issues: [#47333](https://github.com/elastic/elasticsearch/issues/47333), [#47714](https://github.com/elastic/elasticsearch/issues/47714))
- [ ]   Geo_point runtime field implementation [#63164](https://github.com/elastic/elasticsearch/pull/63164)

**Machine Learning**

- [ ]   Add new snapshot upgrader API for upgrading older snapshots [#64665](https://github.com/elastic/elasticsearch/pull/64665) (issue: [#64154](https://github.com/elastic/elasticsearch/issues/64154))
- [ ]   Add total ML memory to ML info [#65195](https://github.com/elastic/elasticsearch/pull/65195) (issue: [#64225](https://github.com/elastic/elasticsearch/issues/64225))
- [ ]   Adding result_type and mlcategory fields to category definitions [#63326](https://github.com/elastic/elasticsearch/pull/63326) (issue: [#60108](https://github.com/elastic/elasticsearch/issues/60108))
- [ ]   Provide a way to revert an AD job to an empty snapshot [#65431](https://github.com/elastic/elasticsearch/pull/65431)

**Mapping**

- [ ]   Support unmapped fields in search 'fields' option [#65386](https://github.com/elastic/elasticsearch/pull/65386) (issue: [#63690](https://github.com/elastic/elasticsearch/issues/63690))
- [ ]   Allow MappedFieldType impls to hide themselves from field caps [#63547](https://github.com/elastic/elasticsearch/pull/63547) (issue: [#63446](https://github.com/elastic/elasticsearch/issues/63446))
- [ ]  ~~Enable collapse on unsigned_long field [#63495](https://github.com/elastic/elasticsearch/pull/63495) (issue: [#60050](https://github.com/elastic/elasticsearch/issues/60050))~~
- [x]   Introduce runtime section in mappings [#62906](https://github.com/elastic/elasticsearch/pull/62906) (issue: [#59332](https://github.com/elastic/elasticsearch/issues/59332))

**Search**

- [x]   Add runtime_mappings to search request [#64374](https://github.com/elastic/elasticsearch/pull/64374) (issue: [#59332](https://github.com/elastic/elasticsearch/issues/59332)) **PR #5259**
- [x]   Add support for runtime fields [#61776](https://github.com/elastic/elasticsearch/pull/61776) (issue: [#59332](https://github.com/elastic/elasticsearch/issues/59332))
- [ ]   Automatic tie-breaking for sorted queries within a PIT [#65450](https://github.com/elastic/elasticsearch/pull/65450) (issue: [#56828](https://github.com/elastic/elasticsearch/issues/56828))

**Transform**

- [x]   Add new exclude_generated flag to GET transform [#63093](https://github.com/elastic/elasticsearch/pull/63093) (issue: [#63055](https://github.com/elastic/elasticsearch/issues/63055))
- [ ]   Add support for "missing" aggregation [#63651](https://github.com/elastic/elasticsearch/pull/63651)
- [ ]   Add support for median absolute deviation [#64634](https://github.com/elastic/elasticsearch/pull/64634)
- [x]  [Transform] use ISO dates in output instead of epoch millis [#65584](https://github.com/elastic/elasticsearch/pull/65584) - Introduces changing behaviour and new dates_as_epoch_millis setting.

### Bug fixes

**Features/Indices APIs**

- [x]   Fix remove alias with must_exist [#65141](https://github.com/elastic/elasticsearch/pull/65141) (issues: [#58100](https://github.com/elastic/elasticsearch/issues/58100), [#62642](https://github.com/elastic/elasticsearch/issues/62642))

**Search**

- [ ]   Add explanation to runtime field query [#63429](https://github.com/elastic/elasticsearch/pull/63429)
- [ ]   Drop boost from runtime distance feature query [#63949](https://github.com/elastic/elasticsearch/pull/63949) (issue: [#63767](https://github.com/elastic/elasticsearch/issues/63767))

# 7.10 Remaining Items

### **New features**

**Aggregations**

- [x] Add rate aggregation [#61369](https://github.com/elastic/elasticsearch/pull/61369) (issue: [#60674](https://github.com/elastic/elasticsearch/issues/60674)) - **PR #5206**

**Features/Features**

- [x] Add data tiers (hot, warm, cold, frozen) as custom node roles [#60994](https://github.com/elastic/elasticsearch/pull/60994) (issue: [#60848](https://github.com/elastic/elasticsearch/issues/60848))

**Features/ILM+SLM**

- [ ] ILM migrate data between tiers [#61377](https://github.com/elastic/elasticsearch/pull/61377) (issue: [#60848](https://github.com/elastic/elasticsearch/issues/60848))
- [ ] ILM: add force-merge step to searchable snapshots action [#60819](https://github.com/elastic/elasticsearch/pull/60819) (issues: [#53488](https://github.com/elastic/elasticsearch/issues/53488), [#56215](https://github.com/elastic/elasticsearch/issues/56215))

**Machine Learning**

- [ ] Implement AucRoc metric for classification [#60502](https://github.com/elastic/elasticsearch/pull/60502) (issue: [#62160](https://github.com/elastic/elasticsearch/issues/62160))

**Mapping**

- [ x] Introduce 64-bit unsigned long field type [#60050](https://github.com/elastic/elasticsearch/pull/60050) (issue: [#32434](https://github.com/elastic/elasticsearch/issues/32434)) **PR #5275**

**Search**

- [x] Add search _fields_ option to support high-level field retrieval [#60100](https://github.com/elastic/elasticsearch/pull/60100) (issues: [#49028](https://github.com/elastic/elasticsearch/issues/49028), [#55363](https://github.com/elastic/elasticsearch/issues/55363)) - **SG WIP (Required for Runtime Fields)**

### **Enhancements**

- [ ] Oidc additional client auth types [#58708](https://github.com/elastic/elasticsearch/pull/58708)

**Authorization**

- [ ] Add more context to index access denied errors [#60357](https://github.com/elastic/elasticsearch/pull/60357) (issue: [#42166](https://github.com/elastic/elasticsearch/issues/42166))

**CRUD**

- [ ] ~~Dedicated threadpool for system index writes [#61655](https://github.com/elastic/elasticsearch/pull/61655)~~

**Cluster Coordination**

- [ ] ~~Provide option to allow writes when master is down [#60605](https://github.com/elastic/elasticsearch/pull/60605)~~

**Distributed**

- [ ] ~~Detect noop of update index settings [#61348](https://github.com/elastic/elasticsearch/pull/61348)~~

**Features/Features**

- [ ] Add aggregation list to node info [#60074](https://github.com/elastic/elasticsearch/pull/60074) (issue: [#52057](https://github.com/elastic/elasticsearch/issues/52057))
- [x] Adding new `require_alias` option to indexing requests [#58917](https://github.com/elastic/elasticsearch/pull/58917) (issue: [#55267](https://github.com/elastic/elasticsearch/issues/55267))

**Features/Ingest**

- [ ] ~~Add network from MaxMind Geo ASN database [#61676](https://github.com/elastic/elasticsearch/pull/61676)~~
- [x] Allow_duplicates option for append processor [#61916](https://github.com/elastic/elasticsearch/pull/61916) (issue: [#57543](https://github.com/elastic/elasticsearch/issues/57543)) - **PR #5208**
- [ ] Configurable output format for date processor [#61324](https://github.com/elastic/elasticsearch/pull/61324) (issue: [#42523](https://github.com/elastic/elasticsearch/issues/42523))
- [ ] Enhance the ingest node simulate verbose output [#60433](https://github.com/elastic/elasticsearch/pull/60433) (issue: [#56004](https://github.com/elastic/elasticsearch/issues/56004))
- [ ] Per processor description for verbose simulate [#58207](https://github.com/elastic/elasticsearch/pull/58207) (issue: [#57906](https://github.com/elastic/elasticsearch/issues/57906))
- [ ] ~~Preserve grok pattern ordering and add sort option [#61671](https://github.com/elastic/elasticsearch/pull/61671) (issue: [#40819](https://github.com/elastic/elasticsearch/issues/40819))~~

**Infra/Core**

- [ ] Add logstash system index APIs [#53350](https://github.com/elastic/elasticsearch/pull/53350)
- [ ] Deprecate REST access to System Indices [#60945](https://github.com/elastic/elasticsearch/pull/60945)

**Infra/Logging**

- [ ] Write deprecation logs to a data stream [#61484](https://github.com/elastic/elasticsearch/pull/61484) (issues: [#46106](https://github.com/elastic/elasticsearch/issues/46106), [#61474](https://github.com/elastic/elasticsearch/issues/61474))

**Machine Learning**

- [ ] Add a "verbose" option to the data frame analytics stats endpoint [#59589](https://github.com/elastic/elasticsearch/pull/59589) (issue: [#59125](https://github.com/elastic/elasticsearch/issues/59125))
- [ ] Add new include flag to get trained models API for model training metadata [#61922](https://github.com/elastic/elasticsearch/pull/61922)
- [ ] Add new feature_processors field for data frame analytics [#60528](https://github.com/elastic/elasticsearch/pull/60528) (issue: [#59327](https://github.com/elastic/elasticsearch/issues/59327))
- [ ] Add new n_gram_encoding custom processor [#61578](https://github.com/elastic/elasticsearch/pull/61578)
- [ ] Calculate total feature importance to store with model metadata [#1387](https://github.com/elastic/ml-cpp/pull/1387)
- [ ] Change outlier detection feature_influence format to array with nested objects [#1475](https://github.com/elastic/ml-cpp/pull/1475), [#62068](https://github.com/elastic/elasticsearch/pull/62068)

**Mapping**

- [x] Add field type for version strings [#59773](https://github.com/elastic/elasticsearch/pull/59773) (issue: [#48878](https://github.com/elastic/elasticsearch/issues/48878))
- [ ] Allow [null] values in [null_value] [#61798](https://github.com/elastic/elasticsearch/pull/61798) (issues: [#7978](https://github.com/elastic/elasticsearch/issues/7978), [#58823](https://github.com/elastic/elasticsearch/issues/58823))
- [ ] Allow metadata fields in the _source [#61590](https://github.com/elastic/elasticsearch/pull/61590) (issue: [#58339](https://github.com/elastic/elasticsearch/issues/58339))

**Search**

- [ ] Add case insensitive flag for "term" family of queries [#61596](https://github.com/elastic/elasticsearch/pull/61596) (issue: [#61546](https://github.com/elastic/elasticsearch/issues/61546))
- [ ] Add case insensitive support for regex queries [#59441](https://github.com/elastic/elasticsearch/pull/59441)
- [ ] Tweak toXContent implementation of ParametrizedFieldMapper [#59968](https://github.com/elastic/elasticsearch/pull/59968)
- [ ] Implement fields value fetching for the `text`, `search_as_you_type` and `token_count` field types [#63515](https://github.com/elastic/elasticsearch/pull/63515)

**Snapshot/Restore**

- [ ] Add repositories metering API [#60371](https://github.com/elastic/elasticsearch/pull/60371)
- [x] Clone Snapshot API [#61839](https://github.com/elastic/elasticsearch/pull/61839) - **SG WIP**
- [ ] Introduce index based snapshot blob cache for Searchable Snapshots [#60522](https://github.com/elastic/elasticsearch/pull/60522)

**Store**

- [ ] Report more details of unobtainable ShardLock [#61255](https://github.com/elastic/elasticsearch/pull/61255) (issue: [#38807](https://github.com/elastic/elasticsearch/issues/38807))

**Transform**

- [ ] Add support for missing bucket [#59591](https://github.com/elastic/elasticsearch/pull/59591) (issues: [#42941](https://github.com/elastic/elasticsearch/issues/42941), [#55102](https://github.com/elastic/elasticsearch/issues/55102))

### **Bug fixes**

**Aggregations**

- [ ] Fix AOOBE when setting min_doc_count to 0 in significant_terms [#60823](https://github.com/elastic/elasticsearch/pull/60823) (issues: [#60683](https://github.com/elastic/elasticsearch/issues/60683), [#60824](https://github.com/elastic/elasticsearch/issues/60824))
- [ ] Make sure non-collecting aggs include sub-aggs [#64214](https://github.com/elastic/elasticsearch/pull/64214) (issue: [#64142](https://github.com/elastic/elasticsearch/issues/64142))
- [ ] Fix broken parent and child aggregator [#63811](https://github.com/elastic/elasticsearch/pull/63811)

**CRUD**

- [ ] Propagate forceExecution when acquiring permit [#60634](https://github.com/elastic/elasticsearch/pull/60634) (issue: [#60359](https://github.com/elastic/elasticsearch/issues/60359))

**Distributed**

- [ ] ~~Fix cluster health when closing [#61709](https://github.com/elastic/elasticsearch/pull/61709)~~

**Features/Stats**

- [ ] Remove sporadic min/max usage estimates from stats [#59755](https://github.com/elastic/elasticsearch/pull/59755)

**Features/Watcher**

- [ ] Correct the query dsl for watching elasticsearch version [#58321](https://github.com/elastic/elasticsearch/pull/58321) (issue: [#58261](https://github.com/elastic/elasticsearch/issues/58261))
- [ ] Fix passing params to template or script failed in watcher [#58559](https://github.com/elastic/elasticsearch/pull/58559) (issue: [#57625](https://github.com/elastic/elasticsearch/issues/57625))

**Machine Learning**

- [ ] Get data frame analytics jobs stats API can return multiple responses if more than one error [#60900](https://github.com/elastic/elasticsearch/pull/60900) (issue: [#60876](https://github.com/elastic/elasticsearch/issues/60876))
- [ ] Correct the anomaly detection job model state `min_version` [#1546](https://github.com/elastic/ml-cpp/pull/1546)

**Mapping**

- [ ] Improve _ignore_malformed_ handling for dates [#60211](https://github.com/elastic/elasticsearch/pull/60211) (issue: [#52634](https://github.com/elastic/elasticsearch/issues/52634))

**Network**

- [ ] Suppress noisy SSL exceptions [#61359](https://github.com/elastic/elasticsearch/pull/61359)

**Search**

- [ ] Allows nanosecond resolution in search_after [#60328](https://github.com/elastic/elasticsearch/pull/60328) (issue: [#52424](https://github.com/elastic/elasticsearch/issues/52424))
