### ISSUE TITLE
7.12.0 Meta Ticket

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elasticsearch-net#5337]
# Priority Items for 7.12.0

These are the priority items for 7.12.0. The need further review and refinement to identify if changes are required in the client to fully support these use cases.

- [x] Remove beta notices from runtime fields types.
- [x] Add the frozen tier node role and ILM phase [#68605](https://github.com/elastic/elasticsearch/pull/68605) (issue: [#60848](https://github.com/elastic/elasticsearch/issues/60848)) - **PR #5354**
- [x] Fingerprint ingest processor [#68415](https://github.com/elastic/elasticsearch/pull/68415) (issue: [#53578](https://github.com/elastic/elasticsearch/issues/53578)) - **PR #5345**
- [x] Network community_id processor for ingest pipelines [#66534](https://github.com/elastic/elasticsearch/pull/66534) (issue: [#55685](https://github.com/elastic/elasticsearch/issues/55685)) - **PR #5347**
- [x] Network direction processor [#66644](https://github.com/elastic/elasticsearch/pull/66644) - **PR #5360**
- [x] Sort field tiebreaker for PIT (point in time) readers [#66093](https://github.com/elastic/elasticsearch/pull/66093) (issue: [#56828](https://github.com/elastic/elasticsearch/issues/56828)) - **PR #5374**
- [x] Add processor architectures to cluster stats [#68264](https://github.com/elastic/elasticsearch/pull/68264) - **PR #5338**
- [x] Add multi_terms aggs [#67597](https://github.com/elastic/elasticsearch/pull/67597) (issue: [#65623](https://github.com/elastic/elasticsearch/issues/65623)) - **PR #5372**
- [x] Add max_single_primary_size as a condition for the rollover index API [#67842](https://github.com/elastic/elasticsearch/pull/67842) (issue: [#63026](https://github.com/elastic/elasticsearch/issues/63026)) - **PR #5353**
- [x] Add support for search-time runtime fields #67643 (issue: #65147) - **PR #5377**
- [x] Add linear function to rank_feature query [#67438](https://github.com/elastic/elasticsearch/pull/67438) (issue: [#49859](https://github.com/elastic/elasticsearch/issues/49859)) - **PR #5373**
- [x] Add query param to limit highlighting to specified length [#67325](https://github.com/elastic/elasticsearch/pull/67325) (issue: [#52155](https://github.com/elastic/elasticsearch/issues/52155)) - **PR #5383**
- [x] QL: "fields" api implementation in QL [#68802](https://github.com/elastic/elasticsearch/pull/68802) (issue: [#67727](https://github.com/elastic/elasticsearch/issues/67727)) - No changes required. Client can already support the 7.12 format

# Secondary Items

Additional items for consideration and further refinement.

### Breaking changes

**Mapping**

- [ ] Returning nested data in fields API [#67432](https://github.com/elastic/elasticsearch/pull/67432) (issue: [#63709](https://github.com/elastic/elasticsearch/issues/63709))

### New features

**Authorization**

- [ ] Add a cluster privilege to cancel tasks and delete async searches [#68679](https://github.com/elastic/elasticsearch/pull/68679) (issue: [#67965](https://github.com/elastic/elasticsearch/issues/67965))

**Features/ILM+SLM**

- [ ] Add support for partial searchable snapshots to ILM [#68714](https://github.com/elastic/elasticsearch/pull/68714) (issues: [#68509](https://github.com/elastic/elasticsearch/issues/68509), [#68605](https://github.com/elastic/elasticsearch/issues/68605))
- [ ] Support max_single_primary_size in Resize Action and exposed in ILM [#67705](https://github.com/elastic/elasticsearch/pull/67705) (issue: [#65714](https://github.com/elastic/elasticsearch/issues/65714))

**Search**

- [ ] Add minimum compatibility version to SearchRequest [#65896](https://github.com/elastic/elasticsearch/pull/65896) (issue: [#63304](https://github.com/elastic/elasticsearch/issues/63304))

**Snapshot/Restore**

- [ ] Add partial searchable snapshot support for a frozen tier [#68509](https://github.com/elastic/elasticsearch/pull/68509)

### Enhancements

**MULTIPLE AREA LABELS**

- [ ] Introduce eql search status API [#68065](https://github.com/elastic/elasticsearch/pull/68065) (issue: [#66955](https://github.com/elastic/elasticsearch/issues/66955))

**Authorization**

- [ ] Phase 2 support for operator privileges: Cluster settings [#66684](https://github.com/elastic/elasticsearch/pull/66684)

**Features/Ingest**

- [ ] Configurable MIME type for mustache template encoding on set processor [#65314](https://github.com/elastic/elasticsearch/pull/65314) (issue: [#65115](https://github.com/elastic/elasticsearch/issues/65115))

**Features/Stats**

- [ ] Make GET _cluster/stats cancellable [#68676](https://github.com/elastic/elasticsearch/pull/68676) (issue: [#55550](https://github.com/elastic/elasticsearch/issues/55550))

**Geo**

- [ ] Implement IndexOrDocValuesQuery for geo_shape field [#64688](https://github.com/elastic/elasticsearch/pull/64688)

**Infra/Core**

- [ ] Introduce "Feature States" for managing snapshots of system indices [#63513](https://github.com/elastic/elasticsearch/pull/63513) (issue: [#61657](https://github.com/elastic/elasticsearch/issues/61657))

**Machine Learning**

- [ ] Add new multi custom processor for data frame analytics and model inference [#67362](https://github.com/elastic/elasticsearch/pull/67362)
- [ ] Improve resuming a data frame analytics job stopped during inference [#67623](https://github.com/elastic/elasticsearch/pull/67623)
- [ ] Move find file structure to a new API endpoint [#67123](https://github.com/elastic/elasticsearch/pull/67123) (issue: [#67001](https://github.com/elastic/elasticsearch/issues/67001))

**Search**

- [ ] Add grok and dissect methods to runtime fields [#68088](https://github.com/elastic/elasticsearch/pull/68088) (issue: [#67825](https://github.com/elastic/elasticsearch/issues/67825))

**Snapshot/Restore**

- [ ] Add ClusterUUID to RepositoryData [#68002](https://github.com/elastic/elasticsearch/pull/68002)

**Transform**

- [ ] Implement retention policy to delete data from a transform [#67832](https://github.com/elastic/elasticsearch/pull/67832) (issue: [#67916](https://github.com/elastic/elasticsearch/issues/67916))
- [ ] Report last search time in transform stats [#66718](https://github.com/elastic/elasticsearch/pull/66718) (issues: [#66367](https://github.com/elastic/elasticsearch/issues/66367), [#66410](https://github.com/elastic/elasticsearch/issues/66410), [#66718](https://github.com/elastic/elasticsearch/issues/66718))
- [ ] [Transform] refactor cat transform to show more useful information [#68232](https://github.com/elastic/elasticsearch/pull/68232) (issues: [#66367](https://github.com/elastic/elasticsearch/issues/66367), [#66718](https://github.com/elastic/elasticsearch/issues/66718))

### Bug fixes

**Infra/Core**

- [ ] Allow the "**,-**" ("no-index") pattern for destructive actions when destructive_requires_name is true [#68021](https://github.com/elastic/elasticsearch/pull/68021) (issue: [#67958](https://github.com/elastic/elasticsearch/issues/67958))

**Comment by stevejgordon** [comment]
Closing as we've implemented the priority features for 7.12.0
