### ISSUE TITLE
7.13.0 Meta Ticket

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elasticsearch-net#5584]
# Priority Items for 7.13.0

These are the priority items for 7.13.0. The need further review and refinement to identify if changes are required in the client to fully support these use cases.

- [x] Registered domain processor [#67611](https://github.com/elastic/elasticsearch/pull/67611) - **PR #5616**
- [x] Convert processor supports validation of IPv4/IPv6 addresses [#69989](https://github.com/elastic/elasticsearch/pull/69989) (issue: [#36145](https://github.com/elastic/elasticsearch/issues/36145)) - **PR #5588**
- [x] Introduce combined_fields query [#71213](https://github.com/elastic/elasticsearch/pull/71213) (issue: [#41106](https://github.com/elastic/elasticsearch/issues/41106)) - **PR #5619**
- [x] Network direction processor additions [#68712](https://github.com/elastic/elasticsearch/pull/68712) - **PR #5603**
- [x] Summary option for listing ingest pipelines without their definitions [#69756](https://github.com/elastic/elasticsearch/pull/69756) (issue: [#31954](https://github.com/elastic/elasticsearch/issues/31954))
- [x] Adds runtime_mappings to SQL requests [#71356](https://github.com/elastic/elasticsearch/pull/71356) (issue: [#68116](https://github.com/elastic/elasticsearch/issues/68116)) - **PR #5626**
- [x] Add calculated numeric fields [#69531](https://github.com/elastic/elasticsearch/pull/69531) - **PR #5622**
- [x] New queryable "_tier" metadata field [#69288](https://github.com/elastic/elasticsearch/pull/69288) (issue: [#68135](https://github.com/elastic/elasticsearch/issues/68135)) - **PR #5606**
- [x] Add positive_score_impact to rank_features type [#69994](https://github.com/elastic/elasticsearch/pull/69994) (issue: [#68619](https://github.com/elastic/elasticsearch/issues/68619)) - **PR #5607**
- [ ] ~~Add support for geo_line aggregation in pivot function [#69299](https://github.com/elastic/elasticsearch/pull/69299)~~
- [ ] ~~Support fetching _tier field value [#71379](https://github.com/elastic/elasticsearch/pull/71379) (issues: [#63569](https://github.com/elastic/elasticsearch/issues/63569), [#68135](https://github.com/elastic/elasticsearch/issues/68135))~~
- [x] Allow format sort values of date fields [#70357](https://github.com/elastic/elasticsearch/pull/70357) (issue: [#69192](https://github.com/elastic/elasticsearch/issues/69192)) - **PR #5610**

#### Once EQL APIs are added
- [x] Adds "fields" request field to the eql request [#68962](https://github.com/elastic/elasticsearch/pull/68962) (issue: [#68115](https://github.com/elastic/elasticsearch/issues/68115)) - **PR #5658**
- [x] Adds runtime_mappings to EQL requests [#71356](https://github.com/elastic/elasticsearch/pull/71356) (issue: [#68116](https://github.com/elastic/elasticsearch/issues/68116)) - **PR #5658**

### Missing NEST APIs
- [x] indices.migrate_to_data_stream - **PR #5633**
- [x] indices.promote_data_stream - **PR #5636**
- [x] eql.search - **PR #5658**
- [x] eql.get - **PR #5665**
- [x] eql.delete - **PR #5667**
- [x] eql.get_status - **PR #5663**
- [x] watcher.query_watches - **PR #5680**

# Secondary Items

Additional items for consideration and further refinement.

## New features

**Features/Ingest**
**Machine Learning**

- [ ] Adds new trained model alias API to simplify trained model updates and deployments [#68922](https://github.com/elastic/elasticsearch/pull/68922)

## Enhancements

**Authentication**

- [ ] Service Accounts - Get service account API [#71315](https://github.com/elastic/elasticsearch/pull/71315)
- [ ] Service Accounts - token name in response to Authenticate API [#71382](https://github.com/elastic/elasticsearch/pull/71382)
- [ ] Support metadata on API keys [#70292](https://github.com/elastic/elasticsearch/pull/70292) (issue: [#48182](https://github.com/elastic/elasticsearch/issues/48182))

**Distributed**

- [ ] Add fleet polling API for global checkpoint [#71093](https://github.com/elastic/elasticsearch/pull/71093)

**Features/Ingest**

- [ ] Add stats endpoint to GeoIpDownloader [#70282](https://github.com/elastic/elasticsearch/pull/70282) (issue: [#68920](https://github.com/elastic/elasticsearch/issues/68920))

**Features/Stats**

- [ ] Make indices stats requests cancellable [#69174](https://github.com/elastic/elasticsearch/pull/69174) (issue: [#55550](https://github.com/elastic/elasticsearch/issues/55550))
- [ ] Make recovery APIs cancellable [#69177](https://github.com/elastic/elasticsearch/pull/69177) (issue: [#55550](https://github.com/elastic/elasticsearch/issues/55550))

**MULTIPLE AREA LABELS**

- [ ] Total data set size in stats [#70625](https://github.com/elastic/elasticsearch/pull/70625) (issue: [#69820](https://github.com/elastic/elasticsearch/issues/69820))

**Machine Learning**

- [ ] Add new delete trained model aliases API [#69195](https://github.com/elastic/elasticsearch/pull/69195)
- [ ] Add runtime mappings to data frame analytics source config [#69183](https://github.com/elastic/elasticsearch/pull/69183) (issue: [#65056](https://github.com/elastic/elasticsearch/issues/65056))
- [ ] Adding new _preview endpoint for data frame analytics [#69453](https://github.com/elastic/elasticsearch/pull/69453)
- [ ] Adding support for composite aggs in anomaly detection [#69970](https://github.com/elastic/elasticsearch/pull/69970)
- [ ] Allow datafeed and job configs for datafeed preview API [#70836](https://github.com/elastic/elasticsearch/pull/70836) (issue: [#70264](https://github.com/elastic/elasticsearch/issues/70264))

**Mapping**

- [ ] Allow specify dynamic templates in bulk request [#69948](https://github.com/elastic/elasticsearch/pull/69948) (issue: [#61939](https://github.com/elastic/elasticsearch/issues/61939))
- [ ] Expose if a field is a metadata field in the field capabilities response [#69977](https://github.com/elastic/elasticsearch/pull/69977)
- [ ] Output script stats for indexed fields [#71219](https://github.com/elastic/elasticsearch/pull/71219)
- [ ] Support fetching flattened subfields [#70916](https://github.com/elastic/elasticsearch/pull/70916) (issue: [#70605](https://github.com/elastic/elasticsearch/issues/70605))

### Missing NEST APIs
- [ ] autoscaling.get_autoscaling_capacity
- [ ] features.get_features
- [ ] features.reset_features
- [ ] ml.delete_trained_model_alias
- [ ] ml.put_trained_model_alias
- [ ] ml.preview_data_frame_analytics
- [ ] ml.upgrade_job_snapshot
- [ ] fleet.global_checkpoints
- [ ] ingest.geo_ip_stats
- [ ] logstash.delete_pipeline
- [ ] logstash.get_pipeline
- [ ] logstash.put_pipeline
- [ ] rollup.rollup
- [ ] searchable_snapshots.cache_stats
- [ ] security.clear_cached_service_tokens
- [ ] security.create_service_token
- [ ] security.delete_service_token
- [ ] security.get_service_accounts
- [ ] security.get_service_credentials
- [ ] shutdown.delete_node
- [ ] shutdown.get_node
- [ ] shutdown.put_node
- [ ] text_structure.find_structure

**Comment by stevejgordon** [comment]
Priority items completed for 7.13.0.
