### ISSUE TITLE
7.14.0 Meta Ticket

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elasticsearch-net#5776]
# Priority Items

## Deprecations

**Analysis**

- [x] Deprecate setting version on analyzers [#74073](https://github.com/elastic/elasticsearch/pull/74073) - **PR #5815**

**Features/Indices APIs**

- [x] Deprecate freeze index API [#72618](https://github.com/elastic/elasticsearch/pull/72618) (issue: [#70192](https://github.com/elastic/elasticsearch/issues/70192)) - REST SPEC PR #https://github.com/elastic/elasticsearch/pull/74983

## New features

**Mapping**

- [x] Add match_only_text, a space-efficient variant of text [#66172](https://github.com/elastic/elasticsearch/pull/66172) (issue: [#64467](https://github.com/elastic/elasticsearch/issues/64467)) - **PR #5801**

**SQL**

- [x] Introduce an async querying mode for SQL [#73991](https://github.com/elastic/elasticsearch/pull/73991) (issue: [#71041](https://github.com/elastic/elasticsearch/issues/71041)) - MISSING REST SPEC

## Enhancements

**Aggregations**

- [x] Add keep_values gap policy [#73297](https://github.com/elastic/elasticsearch/pull/73297) (issue: [#27377](https://github.com/elastic/elasticsearch/issues/27377)) - **PR #5802**

**Features/Stats**

- [x] Add fs iotime in Nodes Stats API [#67861](https://github.com/elastic/elasticsearch/pull/67861) (issue: [#67805](https://github.com/elastic/elasticsearch/issues/67805)) - **PR #5793**

**Machine Learning**

- [x] Adding running_state to datafeed stats object [#73926](https://github.com/elastic/elasticsearch/pull/73926) - **PR #5792**

**Task Management**

- [x] Identify cancelled tasks in list tasks API [#72931](https://github.com/elastic/elasticsearch/pull/72931) (issue: [#72907](https://github.com/elastic/elasticsearch/issues/72907)) - **PR #5803**

## Not Classified

**Features/ILM+SLM**

- [x] Add _meta field to ilm policy [#73515](https://github.com/elastic/elasticsearch/pull/73515) (issue: [#70755](https://github.com/elastic/elasticsearch/issues/70755)) - **PR #5812**
- [ ] ~~Add _meta information to built-in ILM policies [#73629](https://github.com/elastic/elasticsearch/pull/73629)~~

# Secondary Items

**CCR**

- [x] Add support for index pattern exclusion in CCR AutoFollow [#72935](https://github.com/elastic/elasticsearch/pull/72935) (issue: [#67686](https://github.com/elastic/elasticsearch/issues/67686)) - **PR #5832**

**Snapshot/Restore**

- [ ] Introduce Next Field in Paginated GetSnapshots Response [#74236](https://github.com/elastic/elasticsearch/pull/74236) (issue: [#73952](https://github.com/elastic/elasticsearch/issues/73952))
- [ ] Pagination and Sorting for Get Snapshots API [#73952](https://github.com/elastic/elasticsearch/pull/73952)

**Security**

- [ ] Add REST API specification for SAML APIs [#72839](https://github.com/elastic/elasticsearch/pull/72839) (issue: [#67189](https://github.com/elastic/elasticsearch/issues/67189))

**Comment by stevejgordon** [comment]
Completed priority items for 7.14.0
