### ISSUE TITLE
[DOCS] Documentation for v8 Meta Issue

### ISSUE THREAD

**Issue by stevejgordon** [elastic/elasticsearch-net#7624]
The current v8 documentation is limited and should be significantly expanded to describe features and patterns around usage. This meta issue tracks the high-level topics and coordinates doc-specific issues to focus on iterative improvements and additions. It is not exhaustive, and items are not listed in priority order. If you identify poorly documented or missing topics, please raise a specific issue where it can be discussed and potentially added to this tracking issue if agreed for inclusion.

Goals:
- Provide a good developer experience (new users and those migrating from prior versions).
- Describe patterns rather than attempting to document every endpoint.
- Provide example code which is fully copy-pastable and includes using directives.
- Ensure code is imported from test code, which remains current if changes are introduced.

Non-goals:
- Provide examples for every endpoint, query and aggregation. (Improved code snippets in the Elasticsearch source should cover those).

```[tasklist]
### Documentation topics
- [ ] Supported endpoints, queries and aggregations (aid for migration) 
- [ ] Migration guidance and examples
- [ ] Testing patterns when using the ElasticsearchClient
- [ ] Object initializer syntax vs fluent (descriptor) syntax
- [ ] Search query concepts
- [ ] BoolQuery operator (BoolDsl) concepts
- [ ] Aggregation concepts
- [ ] Working with the transport directly (low-level usage)
```
